// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventWrapperGroupUnfrozen } from "../../EventWrapperGroupUnfrozen";

export type GroupIndex_UnfreezeGroup_Response = { "Success": EventWrapperGroupUnfrozen } | "ChatNotFrozen" | "ChatNotFound" | "NotAuthorized" | { "InternalError": string };
