// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageContentInitial } from "../../shared/MessageContentInitial";
import type { MessageId } from "../../shared/MessageId";
import type { MessageIndex } from "../../shared/MessageIndex";

export type GroupEditMessageArgs = { thread_root_message_index?: MessageIndex | undefined, message_id: MessageId, content: MessageContentInitial, block_level_markdown?: boolean | undefined, 
/**
 * @default false
 */
new_achievement: boolean, correlation_id: bigint, };
