// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupSummaryUpdatesSuccessResult } from "./GroupSummaryUpdatesSuccessResult";

export type GroupSummaryUpdatesResponse = { "Success": GroupSummaryUpdatesSuccessResult } | "SuccessNoUpdates" | "CallerNotInGroup";
