// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "../../shared/CommunityId";
import type { VerifiedCredentialGateArgs } from "../../shared/VerifiedCredentialGateArgs";

export type LocalUserIndexJoinCommunityArgs = { community_id: CommunityId, invite_code?: bigint, verified_credential_args?: VerifiedCredentialGateArgs, };
