// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityDeleteMessageSuccessResult } from "./CommunityDeleteMessageSuccessResult";

export type CommunityDeleteMessageResponse = { "Success": CommunityDeleteMessageSuccessResult } | "UserNotInCommunity" | "ChannelNotFound" | "UserNotInChannel" | "NotAuthorized" | "MessageNotFound" | "MessageHardDeleted";
