// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldTooLongResult } from "../../shared/FieldTooLongResult";
import type { FieldTooShortResult } from "../../shared/FieldTooShortResult";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";
import type { UserCreateCommunitySuccessResult } from "./UserCreateCommunitySuccessResult";

export type UserCreateCommunityResponse = { "Success": UserCreateCommunitySuccessResult } | { "NameTooShort": FieldTooShortResult } | { "NameTooLong": FieldTooLongResult } | "NameReserved" | { "DescriptionTooLong": FieldTooLongResult } | { "RulesTooShort": FieldTooShortResult } | { "RulesTooLong": FieldTooLongResult } | { "AvatarTooBig": FieldTooLongResult } | { "BannerTooBig": FieldTooLongResult } | "AccessGateInvalid" | { "MaxCommunitiesCreated": TSNumberWithDefault } | "NameTaken" | "Throttled" | "UserSuspended" | "Unauthorized" | "DefaultChannelsInvalid" | { "InternalError": string };
