// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupCanisterGroupChatSummary } from "../../shared/GroupCanisterGroupChatSummary";

export type GroupSummarySuccessResult = { summary: GroupCanisterGroupChatSummary, };
