// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupIndexExploreCommunitiesArgs = { search_term?: string | undefined, languages: Array<string>, page_index: number, page_size: number, include_moderation_flags: number, };
