// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityMatch } from "../../shared/CommunityMatch";

export type GroupIndexExploreCommunitiesSuccessResult = { 
/**
 * @default []
 */
matches: Array<CommunityMatch>, 
/**
 * @default 0
 */
total: number, };
