// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityMatch } from "../../shared/CommunityMatch";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type GroupIndexExploreCommunitiesSuccessResult = { 
/**
 * @default []
 */
matches: Array<CommunityMatch>, total: TSNumberWithDefault, };
