// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserChitEventsArgs = { from?: bigint | undefined, to?: bigint | undefined, skip?: number | undefined, max: number, ascending: boolean, };
