// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBoolWithDefault } from "../../shared/TSBoolWithDefault";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type UserChitEventsArgs = { from?: bigint | undefined, to?: bigint | undefined, skip?: number | undefined, max: TSNumberWithDefault, ascending: TSBoolWithDefault, };
