// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndexReferralMetricsReferralMetrics } from "./UserIndexReferralMetricsReferralMetrics";

export type UserIndexReferralMetricsResponse = { "Success": UserIndexReferralMetricsReferralMetrics };
