// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserIndexReferralMetricsReferralMetrics = { users_who_referred: number, users_who_referred_paid_diamond: number, users_who_referred_unpaid_diamond: number, users_who_referred_90_percent_unpaid_diamond: number, referrals_of_paid_diamond: number, referrals_of_unpaid_diamond: number, referrals_other: number, icp_raised_by_referrals_to_paid_diamond: number, };
