// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PushEventResult } from "../../shared/PushEventResult";

export type UserRemoveReactionResponse = "Success" | { "SuccessV2": PushEventResult } | "NoChange" | "MessageNotFound" | "ChatNotFound" | "UserSuspended";
