// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExchangeId } from "../../shared/ExchangeId";

export type RegistryAddRemoveSwapProviderArgs = { swap_provider: ExchangeId, add: boolean, };
