// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupUndeleteMessagesSuccessResult } from "./GroupUndeleteMessagesSuccessResult";

export type GroupUndeleteMessagesResponse = { "Success": GroupUndeleteMessagesSuccessResult } | "CallerNotInGroup" | "MessageNotFound" | "UserSuspended" | "UserLapsed" | "ChatFrozen";
