// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "../../shared/MessageId";
import type { MessageIndex } from "../../shared/MessageIndex";
import type { TSBoolWithDefault } from "../../shared/TSBoolWithDefault";

export type CommunityAcceptP2pSwapArgs = { channel_id: bigint, thread_root_message_index?: MessageIndex | undefined, message_id: MessageId, pin?: string | undefined, new_achievement: TSBoolWithDefault, };
