// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityUpdateCommunitySuccessResult } from "./CommunityUpdateCommunitySuccessResult";
import type { FieldTooLongResult } from "../../shared/FieldTooLongResult";
import type { FieldTooShortResult } from "../../shared/FieldTooShortResult";

export type CommunityUpdateCommunityResponse = { "SuccessV2": CommunityUpdateCommunitySuccessResult } | "NotAuthorized" | "UserNotInCommunity" | { "NameTooShort": FieldTooShortResult } | { "NameTooLong": FieldTooLongResult } | "NameReserved" | { "DescriptionTooLong": FieldTooLongResult } | { "AvatarTooBig": FieldTooLongResult } | { "BannerTooBig": FieldTooLongResult } | "AccessGateInvalid" | "NameTaken" | "InternalError" | { "RulesTooLong": FieldTooLongResult } | { "RulesTooShort": FieldTooShortResult } | "UserSuspended" | "CommunityFrozen" | "InvalidLanguage" | "UserLapsed";
