// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionUpdateAccessGate } from "../../shared/OptionUpdateAccessGate";
import type { OptionUpdateAccessGateConfig } from "../../shared/OptionUpdateAccessGateConfig";
import type { OptionUpdateDocument } from "../../shared/OptionUpdateDocument";
import type { OptionalCommunityPermissions } from "../../shared/OptionalCommunityPermissions";
import type { UpdatedRules } from "../../shared/UpdatedRules";

export type CommunityUpdateCommunityArgs = { name?: string | undefined, description?: string | undefined, rules?: UpdatedRules | undefined, 
/**
 * @default NoChange
 */
avatar: OptionUpdateDocument, 
/**
 * @default NoChange
 */
banner: OptionUpdateDocument, permissions?: OptionalCommunityPermissions | undefined, 
/**
 * @default NoChange
 */
gate: OptionUpdateAccessGate, 
/**
 * @default NoChange
 */
gate_config: OptionUpdateAccessGateConfig, public?: boolean | undefined, primary_language?: string | undefined, };
