// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupIndex_ActiveGroups_SuccessResult } from "./GroupIndex_ActiveGroups_SuccessResult";

export type GroupIndex_ActiveGroups_Response = { "Success": GroupIndex_ActiveGroups_SuccessResult };
