// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "../../ChatId";
import type { CommunityId } from "../../CommunityId";
import type { DeletedCommunityInfo } from "../../DeletedCommunityInfo";
import type { DeletedGroupInfo } from "../../DeletedGroupInfo";

export type GroupIndex_ActiveGroups_SuccessResult = { timestamp: bigint, active_groups: Array<ChatId>, active_communities: Array<CommunityId>, deleted_groups: Array<DeletedGroupInfo>, deleted_communities: Array<DeletedCommunityInfo>, };
