// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicGroupSummary } from "../../shared/PublicGroupSummary";
import type { TSBoolWithDefault } from "../../shared/TSBoolWithDefault";

export type GroupPublicSummarySuccessResult = { summary: PublicGroupSummary, is_invited: TSBoolWithDefault, };
