// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndex_ReferralMetrics_ReferralMetrics } from "./UserIndex_ReferralMetrics_ReferralMetrics";

export type UserIndex_ReferralMetrics_Response = { "Success": UserIndex_ReferralMetrics_ReferralMetrics };
