// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "../../shared/MessageIndex";
import type { TSBoolWithDefault } from "../../shared/TSBoolWithDefault";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";
import type { VoteOperation } from "../../shared/VoteOperation";

export type GroupRegisterPollVoteArgs = { thread_root_message_index?: MessageIndex | undefined, message_index: TSNumberWithDefault, poll_option: TSNumberWithDefault, operation: VoteOperation, new_achievement: TSBoolWithDefault, correlation_id: bigint, };
