// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "../../shared/MessageIndex";

export type CommunityEventsWindowArgs = { channel_id: bigint, thread_root_message_index?: MessageIndex, mid_point: MessageIndex, max_messages: number, max_events: number, latest_known_update?: bigint, };
