// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chat } from "../../shared/Chat";

export type UserArchiveUnarchiveChatsArgs = { 
/**
 * @default []
 */
to_archive: Array<Chat>, 
/**
 * @default []
 */
to_unarchive: Array<Chat>, };
