// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chat } from "../../shared/Chat";

export type UserArchiveUnarchiveChatsArgs = { to_archive: Array<Chat>, to_unarchive: Array<Chat>, };
