// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserArchiveUnarchiveChatsPartialSuccessResult } from "./UserArchiveUnarchiveChatsPartialSuccessResult";

export type UserArchiveUnarchiveChatsResponse = "Success" | { "PartialSuccess": UserArchiveUnarchiveChatsPartialSuccessResult } | "Failure" | "UserSuspended";
