// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "../../shared/ChannelId";
import type { MessageContentInitial } from "../../shared/MessageContentInitial";
import type { MessageId } from "../../shared/MessageId";
import type { MessageIndex } from "../../shared/MessageIndex";

export type CommunityEditMessageArgs = { channel_id: ChannelId, thread_root_message_index?: MessageIndex, message_id: MessageId, content: MessageContentInitial, block_level_markdown?: boolean, new_achievement: boolean, };
