// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiamondMembershipFees } from "../../DiamondMembershipFees";

export type UserIndex_SetDiamondMembershipFees_Args = { fees: DiamondMembershipFees, };
