// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiamondMembershipFees } from "../../shared/DiamondMembershipFees";

export type userIndexSetDiamondMembershipFeesArgs = { fees: DiamondMembershipFees, };
