// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserIndexUpdateBotResponse = "Success" | "PrincipalInvalid" | "PrincipalAlreadyUsed" | "AvatarInvalid" | "EndpointInvalid" | "BotNotFound" | "BotSuspended" | "NotAuthorised" | "OwnerNotFound" | "OwnerSuspended" | "NewOwnerNotFound" | "NewOwnerSuspended" | "DescriptionTooLong" | "TooManyCommands";
