// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotDefinition } from "../../shared/BotDefinition";
import type { OptionUpdateString } from "../../shared/OptionUpdateString";
import type { TSPrincipal } from "../../shared/TSPrincipal";
import type { UserId } from "../../shared/UserId";

export type UserIndexUpdateBotArgs = { bot_id: UserId, owner?: UserId, principal?: TSPrincipal, avatar: OptionUpdateString, endpoint?: string, definition?: BotDefinition, };
