// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalUserIndexInstallBotResponse = "Success" | "Frozen" | "NotAuthorized" | "AlreadyAdded" | { "InternalError": string };
