// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chat } from "../../shared/Chat";
import type { EventIndex } from "../../shared/EventIndex";
import type { MessageIndex } from "../../shared/MessageIndex";

export type UserSetMessageReminderArgs = { chat: Chat, thread_root_message_index?: MessageIndex, event_index: EventIndex, notes?: string, remind_at: bigint, };
