// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupRole } from "../../shared/GroupRole";
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";
import type { UserId } from "../../shared/UserId";

export type GroupChangeRoleArgs = { user_id: UserId, new_role: GroupRole, correlation_id: TSBigIntWithDefault, };
