// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityPermissions } from "../../shared/CommunityPermissions";
import type { Rules } from "../../shared/Rules";
import type { TSBoolWithDefault } from "../../shared/TSBoolWithDefault";

export type GroupConvertIntoCommunityArgs = { rules: Rules, permissions?: CommunityPermissions | undefined, primary_language?: string | undefined, history_visible_to_new_joiners: TSBoolWithDefault, };
