// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommunityCreateUserGroupSuccessResult = { 
/**
 * @default 0
 */
user_group_id: number, };
