// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupIndexExploreBotsSuccessResult } from "./GroupIndexExploreBotsSuccessResult";

export type GroupIndexExploreBotsResponse = { "Success": GroupIndexExploreBotsSuccessResult } | { "TermTooShort": number } | { "TermTooLong": number } | "InvalidTerm";
