// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cryptocurrency } from "../../shared/Cryptocurrency";
import type { DiamondMembershipPlanDuration } from "../../shared/DiamondMembershipPlanDuration";

export type UserIndexPayForDiamondMembershipArgs = { duration: DiamondMembershipPlanDuration, token: Cryptocurrency, expected_price_e8s: bigint, recurring: boolean, };
