// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiamondMembershipSubscription } from "../../shared/DiamondMembershipSubscription";
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";
import type { TSBoolWithDefault } from "../../shared/TSBoolWithDefault";

export type UserIndexPayForDiamondMembershipSuccessResult = { expires_at: TSBigIntWithDefault, pay_in_chat: TSBoolWithDefault, subscription: DiamondMembershipSubscription, proof_jwt: string, };
