// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";
import type { UserIndexPayForDiamondMembershipSuccessResult } from "./UserIndexPayForDiamondMembershipSuccessResult";

export type UserIndexPayForDiamondMembershipResponse = { "Success": UserIndexPayForDiamondMembershipSuccessResult } | "AlreadyLifetimeDiamondMember" | "CurrencyNotSupported" | "PriceMismatch" | "PaymentAlreadyInProgress" | "UserNotFound" | { "InsufficientFunds": TSBigIntWithDefault } | { "TransferFailed": string } | { "InternalError": string };
