// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBoolWithDefault } from "../../shared/TSBoolWithDefault";

export type CommunityRegisterProposalVoteResponse = "Success" | { "AlreadyVoted": TSBoolWithDefault } | "CommunityFrozen" | "UserNotInCommunity" | "UserSuspended" | "ChannelNotFound" | "UserNotInChannel" | "NoEligibleNeurons" | "ProposalMessageNotFound" | "ProposalNotFound" | "ProposalNotAcceptingVotes" | { "InternalError": string } | "UserLapsed";
