// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "../../shared/UserId";

export type UserIndexUserArgs = { user_id?: UserId | undefined, username?: string | undefined, };
