import type { IDL } from "@dfinity/candid";
import {
    _SERVICE,
    AddReactionResponse,
    AddMembersToChannelResponse,
    AddMembersToChannelFailed,
    AddMembersToChannelPartialSuccess,
    UserFailedError,
    UserFailedGateCheck,
    BlockUserResponse,
    ChangeChannelRoleResponse,
    ChangeRoleResponse,
    CommunityRole,
    CommunityPermissionRole,
    CreateChannelResponse,
    DeclineInvitationResponse,
    DeleteChannelResponse,
    DeleteMessagesResponse,
    DeletedMessageResponse,
    DisableInviteCodeResponse,
    EditMessageResponse,
    EventsResponse,
    GroupRole,
    InviteCodeResponse,
    JoinChannelResponse,
    LeaveChannelResponse,
    MakeChannelPrivateResponse,
    MessagesByMessageIndexResponse,
    OptionalCommunityPermissions,
    PinMessageResponse,
    RemoveMemberResponse,
    RemoveMemberFromChannelResponse,
    RemoveReactionResponse,
    EnableInviteCodeResponse,
    RulesResponse,
    SearchChannelResponse,
    SelectedChannelInitialResponse,
    SelectedChannelUpdatesV2Response,
    SendMessageResponse,
    SummaryResponse,
    SummaryUpdatesResponse,
    ToggleMuteChannelNotificationsResponse,
    ToggleMuteNotificationsResponse,
    UnblockUserResponse,
    UndeleteMessagesResponse,
    UpdateChannelResponse,
    UpdateCommunityResponse,
    CommunityCanisterChannelSummary,
    MessageMatch,
    CommunityCanisterCommunitySummary,
    CommunityCanisterCommunitySummaryUpdates,
    CommunityCanisterChannelSummaryUpdates,
    GroupMembershipUpdates,
    CommunityMembershipUpdates,
    ExploreChannelsResponse,
    ChannelMatch,
    SelectedInitialResponse,
    SelectedUpdatesV2Response,
    SelectedInitialSuccess,
    SelectedUpdatesSuccess,
    MessagesByMessageIndexResponse,
    ThreadPreviewsResponse,
    ChannelSummaryResponse,
    RegisterPollVoteResponse,
    ImportGroupResponse,
    GroupCanisterThreadDetails,
    RegisterProposalVoteResponse,
    CreateUserGroupResponse,
    UpdateUserGroupResponse,
    UserGroupDetails,
    DeleteUserGroupsResponse,
    SetMemberDisplayNameResponse,
    VersionedRules,
    FollowThreadResponse,
    UnfollowThreadResponse,
    ClaimPrizeResponse,
    AcceptP2PSwapResponse,
    CancelP2PSwapResponse,
    JoinVideoCallResponse,
    VideoCallParticipantsResponse,
    UserGroup,
    AccessGateConfig,
} from "./types";
export {
    _SERVICE as CommunityService,
    AddReactionResponse as ApiAddReactionResponse,
    AddMembersToChannelResponse as ApiAddMembersToChannelResponse,
    AddMembersToChannelFailed as ApiAddMembersToChannelFailed,
    AddMembersToChannelPartialSuccess as ApiAddMembersToChannelPartialSuccess,
    UserFailedError as ApiUserFailedError,
    UserFailedGateCheck as ApiUserFailedGateCheck,
    BlockUserResponse as ApiBlockUserResponse,
    ChangeChannelRoleResponse as ApiChangeChannelRoleResponse,
    ChangeRoleResponse as ApiChangeRoleResponse,
    CommunityRole as ApiCommunityRole,
    CommunityPermissionRole as ApiCommunityPermissionRole,
    CreateChannelResponse as ApiCreateChannelResponse,
    DeclineInvitationResponse as ApiDeclineInvitationResponse,
    DeleteChannelResponse as ApiDeleteChannelResponse,
    DeleteMessagesResponse as ApiDeleteMessagesResponse,
    DeletedMessageResponse as ApiDeletedMessageResponse,
    DisableInviteCodeResponse as ApiDisableInviteCodeResponse,
    EditMessageResponse as ApiEditMessageResponse,
    EventsResponse as ApiEventsResponse,
    GroupRole as ApiGroupRole,
    InviteCodeResponse as ApiInviteCodeResponse,
    JoinChannelResponse as ApiJoinChannelResponse,
    LeaveChannelResponse as ApiLeaveChannelResponse,
    MakeChannelPrivateResponse as ApiMakeChannelPrivateResponse,
    MessagesByMessageIndexResponse as ApiMessagesByMessageIndexResponse,
    OptionalCommunityPermissions as ApiOptionalCommunityPermissions,
    PinMessageResponse as ApiPinChannelMessageResponse,
    RemoveMemberResponse as ApiRemoveMemberResponse,
    RemoveMemberFromChannelResponse as ApiRemoveMemberFromChannelResponse,
    RemoveReactionResponse as ApiRemoveReactionResponse,
    EnableInviteCodeResponse as ApiEnableInviteCodeResponse,
    RulesResponse as ApiRulesResponse,
    SearchChannelResponse as ApiSearchChannelResponse,
    SelectedChannelInitialResponse as ApiSelectedChannelInitialResponse,
    SelectedChannelUpdatesV2Response as ApiSelectedChannelUpdatesResponse,
    SendMessageResponse as ApiSendMessageResponse,
    SummaryResponse as ApiSummaryResponse,
    SummaryUpdatesResponse as ApiSummaryUpdatesResponse,
    ToggleMuteChannelNotificationsResponse as ApiToggleMuteChannelNotificationsResponse,
    ToggleMuteNotificationsResponse as ApiToggleMuteNotificationsResponse,
    UnblockUserResponse as ApiUnblockUserResponse,
    UndeleteMessagesResponse as ApiUndeleteMessagesResponse,
    UpdateChannelResponse as ApiUpdateChannelResponse,
    UpdateCommunityResponse as ApiUpdateCommunityResponse,
    CommunityCanisterChannelSummary as ApiCommunityCanisterChannelSummary,
    MessageMatch as ApiMessageMatch,
    CommunityCanisterCommunitySummary as ApiCommunityCanisterCommunitySummary,
    CommunityCanisterCommunitySummaryUpdates as ApiCommunityCanisterCommunitySummaryUpdates,
    CommunityCanisterChannelSummaryUpdates as ApiCommunityCanisterChannelSummaryUpdates,
    GroupMembershipUpdates as ApiGroupMembershipUpdates,
    CommunityMembershipUpdates as ApiCommunityMembershipUpdates,
    ExploreChannelsResponse as ApiExploreChannelsResponse,
    ChannelMatch as ApiChannelMatch,
    SelectedInitialResponse as ApiSelectedInitialResponse,
    SelectedUpdatesV2Response as ApiSelectedUpdatesResponse,
    SelectedInitialSuccess as ApiSelectedInitialSuccess,
    SelectedUpdatesSuccess as ApiSelectedUpdatesSuccess,
    MessagesByMessageIndexResponse as ApiMessagesByMessageIndexResponse,
    ThreadPreviewsResponse as ApiThreadPreviewsResponse,
    ChannelSummaryResponse as ApiChannelSummaryResponse,
    RegisterPollVoteResponse as ApiRegisterPollVoteResponse,
    ImportGroupResponse as ApiImportGroupResponse,
    GroupCanisterThreadDetails as ApiGroupCanisterThreadDetails,
    RegisterProposalVoteResponse as ApiRegisterProposalVoteResponse,
    CreateUserGroupResponse as ApiCreateUserGroupResponse,
    UpdateUserGroupResponse as ApiUpdateUserGroupResponse,
    UserGroupDetails as ApiUserGroupDetails,
    DeleteUserGroupsResponse as ApiDeleteUserGroupsResponse,
    SetMemberDisplayNameResponse as ApiSetMemberDisplayNameResponse,
    FollowThreadResponse as ApiFollowThreadResponse,
    UnfollowThreadResponse as ApiUnfollowThreadResponse,
    ClaimPrizeResponse as ApiClaimPrizeResponse,
    AcceptP2PSwapResponse as ApiAcceptP2PSwapResponse,
    CancelP2PSwapResponse as ApiCancelP2PSwapResponse,
    JoinVideoCallResponse as ApiJoinVideoCallResponse,
    VideoCallParticipantsResponse as ApiVideoCallParticipantsResponse,
    UserGroup as ApiUserGroup,
    AccessGateConfig as ApiAccessGateConfig,
};

export const idlFactory: IDL.InterfaceFactory;
