// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingCryptoTransaction } from "../../shared/PendingCryptoTransaction";

export type UserWithdrawCryptoArgs = { withdrawal: PendingCryptoTransaction, pin?: string | undefined, };
