// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletedCryptoTransaction } from "../../shared/CompletedCryptoTransaction";
import type { FailedCryptoTransaction } from "../../shared/FailedCryptoTransaction";
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";

export type UserWithdrawCryptoResponse = { "Success": CompletedCryptoTransaction } | { "TransactionFailed": FailedCryptoTransaction } | "CurrencyNotSupported" | "PinRequired" | { "PinIncorrect": TSBigIntWithDefault } | { "TooManyFailedPinAttempts": TSBigIntWithDefault } | { "InternalError": string };
