// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "../../shared/ChannelId";
import type { MessageId } from "../../shared/MessageId";

export type CommunityVideoCallParticipantsArgs = { channel_id: ChannelId, message_id: MessageId, updated_since?: bigint, };
