// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "../../shared/ChannelId";
import type { OptionUpdateAccessGateConfig } from "../../shared/OptionUpdateAccessGateConfig";
import type { OptionUpdateDocument } from "../../shared/OptionUpdateDocument";
import type { OptionUpdateString } from "../../shared/OptionUpdateString";
import type { OptionUpdateU64 } from "../../shared/OptionUpdateU64";
import type { OptionalGroupPermissions } from "../../shared/OptionalGroupPermissions";
import type { UpdatedRules } from "../../shared/UpdatedRules";

export type CommunityUpdateChannelArgs = { channel_id: ChannelId, name?: string, description?: string, rules?: UpdatedRules, avatar: OptionUpdateDocument, permissions_v2?: OptionalGroupPermissions, events_ttl: OptionUpdateU64, gate_config: OptionUpdateAccessGateConfig, public?: boolean, messages_visible_to_non_members?: boolean, external_url: OptionUpdateString, };
