import type { ApiAddParticipantsResponse, ApiEventsResponse, ApiChangeRoleResponse, ApiRemoveParticipantResponse, ApiSendMessageResponse, ApiUpdateGroupResponse, ApiAddReactionResponse, ApiRemoveReactionResponse, ApiDeleteMessageResponse, ApiEditMessageResponse, ApiSelectedInitialResponse, ApiSelectedUpdatesResponse, ApiRole, ApiMessagesByMessageIndexResponse, ApiMessageEventWrapper, ApiPinMessageResponse, ApiUnpinMessageResponse, ApiSearchGroupChatResponse, ApiMakePrivateResponse, ApiInviteCodeResponse, ApiEnableInviteCodeResponse, ApiDisableInviteCodeResponse, ApiResetInviteCodeResponse, ApiThreadPreviewsResponse, ApiThreadPreview, ApiRegisterPollVoteResponse, ApiRegisterProposalVoteResponse, ApiGroupRules, ApiRulesResponse } from "./candid/idl";
import type { EventsResponse, EventWrapper, GroupChatEvent, AddMembersResponse, SendMessageResponse, RemoveMemberResponse, UpdateGroupResponse, AddRemoveReactionResponse, DeleteMessageResponse, EditMessageResponse, BlockUserResponse, ChangeRoleResponse, GroupChatDetailsResponse, GroupChatDetailsUpdatesResponse, UnblockUserResponse, MemberRole, Message, PinMessageResponse, UnpinMessageResponse, MakeGroupPrivateResponse, InviteCodeResponse, EnableInviteCodeResponse, DisableInviteCodeResponse, ResetInviteCodeResponse, ThreadPreviewsResponse, ThreadPreview, RegisterPollVoteResponse, RegisterProposalVoteResponse, GroupRules, GroupPermissions } from "../../domain/chat/chat";
import type { ApiBlockUserResponse, ApiUnblockUserResponse } from "../group/candid/idl";
import type { SearchGroupChatResponse } from "../../domain/search/search";
import type { OptionalGroupPermissions } from "./candid/types";
export declare function apiRole(role: MemberRole): ApiRole | undefined;
export declare function apiOptionalGroupPermissions(permissions: Partial<GroupPermissions>): OptionalGroupPermissions;
export declare function apiGroupRules(rules: GroupRules): ApiGroupRules;
export declare function groupDetailsUpdatesResponse(candid: ApiSelectedUpdatesResponse): GroupChatDetailsUpdatesResponse;
export declare function groupDetailsResponse(candid: ApiSelectedInitialResponse): GroupChatDetailsResponse;
export declare function makeGroupPrivateResponse(candid: ApiMakePrivateResponse): MakeGroupPrivateResponse;
export declare function unblockUserResponse(candid: ApiUnblockUserResponse): UnblockUserResponse;
export declare function blockUserResponse(candid: ApiBlockUserResponse): BlockUserResponse;
export declare function deleteMessageResponse(candid: ApiDeleteMessageResponse): DeleteMessageResponse;
export declare function addRemoveReactionResponse(candid: ApiAddReactionResponse | ApiRemoveReactionResponse): AddRemoveReactionResponse;
export declare function updateGroupResponse(candid: ApiUpdateGroupResponse): UpdateGroupResponse;
export declare function editMessageResponse(candid: ApiEditMessageResponse): EditMessageResponse;
export declare function sendMessageResponse(candid: ApiSendMessageResponse): SendMessageResponse;
export declare function changeRoleResponse(candid: ApiChangeRoleResponse): ChangeRoleResponse;
export declare function removeMemberResponse(candid: ApiRemoveParticipantResponse): RemoveMemberResponse;
export declare function addMembersResponse(candid: ApiAddParticipantsResponse): AddMembersResponse;
export declare function pinMessageResponse(candid: ApiPinMessageResponse): PinMessageResponse;
export declare function unpinMessageResponse(candid: ApiUnpinMessageResponse): UnpinMessageResponse;
export declare function getMessagesByMessageIndexResponse(candid: ApiMessagesByMessageIndexResponse, chatId: string, threadRootMessageIndex: number | undefined, latestClientEventIndexPreRequest: number | undefined): EventsResponse<Message>;
export declare function messageWrapper(candid: ApiMessageEventWrapper): EventWrapper<Message>;
export declare function getEventsResponse(candid: ApiEventsResponse, chatId: string, threadRootMessageIndex: number | undefined, latestClientEventIndexPreRequest: number | undefined): EventsResponse<GroupChatEvent>;
export declare function searchGroupChatResponse(candid: ApiSearchGroupChatResponse): SearchGroupChatResponse;
export declare function inviteCodeResponse(candid: ApiInviteCodeResponse): InviteCodeResponse;
export declare function enableInviteCodeResponse(candid: ApiEnableInviteCodeResponse): EnableInviteCodeResponse;
export declare function disableInviteCodeResponse(candid: ApiDisableInviteCodeResponse): DisableInviteCodeResponse;
export declare function threadPreview(chatId: string, candid: ApiThreadPreview): ThreadPreview;
export declare function threadPreviewsResponse(candid: ApiThreadPreviewsResponse, chatId: string, latestClientThreadUpdate: bigint | undefined): ThreadPreviewsResponse;
export declare function resetInviteCodeResponse(candid: ApiResetInviteCodeResponse): ResetInviteCodeResponse;
export declare function registerPollVoteResponse(candid: ApiRegisterPollVoteResponse): RegisterPollVoteResponse;
export declare function registerProposalVoteResponse(candid: ApiRegisterProposalVoteResponse): RegisterProposalVoteResponse;
export declare function rulesResponse(candid: ApiRulesResponse): GroupRules | undefined;
