pub mod account_billing;
pub mod action_delivery_outbox;
pub mod action_signing_keyring;
pub mod ai_action_registry;
pub mod ai_app_call_throttle;
pub mod ai_app_card_tokens;
pub mod ai_app_chat_link_tokens;
pub mod ai_app_link_codes;
pub mod ai_app_private_match_tokens;
pub mod ai_app_registry;
pub mod ai_app_scoped_identity;
pub mod ai_app_user_keys;
pub mod authority_reports;
pub mod chit_leaderboard;
pub mod diamond_membership_details;
pub mod external_achievements;
pub mod group_index_event_batch;
pub mod local_user_index_map;
pub mod moderation;
pub mod pending_payments_queue;
pub mod premium_items;
pub mod protected_actions;
pub mod reported_messages;
pub mod storage_index_user_config_batch;
pub mod storage_index_users_to_remove_batch;
pub mod streak_insurance_logs;
pub mod user;
pub mod user_map;

pub const MAX_AVATAR_SIZE: usize = 250_000;
pub const MAX_DESCRIPTION_LEN: usize = 10_000;
pub const MAX_COMMANDS: usize = 100;
