// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessGateConfig } from "../../shared/AccessGateConfig";
import type { AuthToken } from "../../shared/AuthToken";
import type { Document } from "../../shared/Document";
import type { GroupPermissions } from "../../shared/GroupPermissions";
import type { Rules } from "../../shared/Rules";

export type LocalUserIndexBotCreateChannelArgs = { is_public: boolean, name: string, description: string, rules: Rules, avatar?: Document, history_visible_to_new_joiners: boolean, messages_visible_to_non_members: boolean, permissions?: GroupPermissions, events_ttl?: bigint, gate_config?: AccessGateConfig, external_url?: string, auth_token: AuthToken, };
