// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotDefinition } from "../../shared/BotDefinition";
import type { TSPrincipal } from "../../shared/TSPrincipal";
import type { UserId } from "../../shared/UserId";

export type UserIndexRegisterBotArgs = { principal: TSPrincipal, owner: UserId, name: string, avatar?: string, endpoint: string, definition: BotDefinition, };
