// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndexDiamondMembershipFeesDiamondMembershipFees } from "./UserIndexDiamondMembershipFeesDiamondMembershipFees";

export type UserIndexDiamondMembershipFeesResponse = { "Success": Array<UserIndexDiamondMembershipFeesDiamondMembershipFees> };
