// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutonomousConfig } from "../../shared/AutonomousConfig";
import type { BotCommandDefinition } from "../../shared/BotCommandDefinition";
import type { UserId } from "../../shared/UserId";

export type UserIndexBotUpdatesBotSchema = { id: UserId, owner: UserId, name: string, avatar_id?: bigint, endpoint: string, description: string, commands: Array<BotCommandDefinition>, autonomous_config?: AutonomousConfig, last_updated: bigint, };
