// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndex_Users_Result } from "./UserIndex_Users_Result";

export type UserIndex_Users_Response = { "Success": UserIndex_Users_Result };
