// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { userIndexUsersUserGroup } from "./userIndexUsersUserGroup";

export type userIndexUsersArgs = { user_groups: Array<userIndexUsersUserGroup>, users_suspended_since?: bigint, };
