// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "../../shared/MessageId";

export type GroupJoinVideoCallArgs = { message_id: MessageId, new_achievement: boolean, };
