import type { IDL } from "@dfinity/candid";
import {
    _SERVICE,
    CreateChallengeResponse,
    CurrentUserResponse,
    CurrentUserArgs,
    CheckUsernameArgs,
    SetUsernameArgs,
    CheckUsernameResponse,
    SetUsernameResponse,
    SubmitPhoneNumberArgs,
    SubmitPhoneNumberResponse,
    ConfirmPhoneNumberArgs,
    ConfirmPhoneNumberResponse,
    PhoneNumber,
    ResendCodeResponse,
    UsersArgs,
    UsersResponse,
    UserSummary,
    PartialUserSummary,
    SearchArgs,
    SearchResponse,
    RegistrationState,
    UnconfirmedPhoneNumberState,
    CyclesFeeState,
    RegistrationFee,
    RegisterUserResponse,
    PhoneStatus,
    UpgradeStorageResponse,
    RefreshAccountBalanceResponse,
} from "./types";
export {
    _SERVICE as UserIndexService,
    CreateChallengeResponse as ApiCreateChallengeResponse,
    CurrentUserResponse as ApiCurrentUserResponse,
    CurrentUserArgs as ApiCurrentUserArgs,
    SetUsernameArgs as ApiSetUsernameArgs,
    CheckUsernameResponse as ApiCheckUsernameResponse,
    SetUsernameResponse as ApiSetUsernameResponse,
    SubmitPhoneNumberArgs as ApiSubmitPhoneNumberArgs,
    SubmitPhoneNumberResponse as ApiSubmitPhoneNumberResponse,
    ConfirmPhoneNumberArgs as ApiConfirmPhoneNumberArgs,
    ConfirmPhoneNumberResponse as ApiConfirmPhoneNumberResponse,
    PhoneNumber as ApiPhoneNumber,
    ResendCodeResponse as ApiResendCodeResponse,
    UsersArgs as ApiUsersArgs,
    UsersResponse as ApiUsersResponse,
    UserSummary as ApiUserSummary,
    PartialUserSummary as ApiPartialUserSummary,
    SearchArgs as ApiSearchArgs,
    SearchResponse as ApiSearchResponse,
    UpgradeCanisterResponse as ApiUpgradeCanisterResponse,
    RegistrationState as ApiRegistrationState,
    UnconfirmedPhoneNumberState as ApiUnconfirmedPhoneNumberState,
    CyclesFeeState as ApiCyclesFeeState,
    RegistrationFee as ApiRegistrationFee,
    RegisterUserResponse as ApiRegisterUserResponse,
    PhoneStatus as ApiPhoneStatus,
    UpgradeStorageResponse as ApiUpgradeStorageResponse,
    RefreshAccountBalanceResponse as ApiRefreshAccountBalanceResponse,
};

export const idlFactory: IDL.InterfaceFactory;
