// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndex_ChitLeaderboard_ChitUserBalance } from "./UserIndex_ChitLeaderboard_ChitUserBalance";

export type UserIndex_ChitLeaderboard_Response = { "Success": Array<UserIndex_ChitLeaderboard_ChitUserBalance> };
