// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndexChitLeaderboardChitUserBalance } from "./UserIndexChitLeaderboardChitUserBalance";

export type UserIndexChitLeaderboardResponse = { "Success": Array<UserIndexChitLeaderboardChitUserBalance> };
