// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "../../UserId";

export type UserIndex_SuspendUser_Args = { user_id: UserId, duration: bigint | null, reason: string, };
