// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommunityDeleteChannelResponse = "Success" | "CommunityFrozen" | "UserSuspended" | "UserNotInCommunity" | "ChannelNotFound" | "UserNotInChannel" | "NotAuthorized" | "UserLapsed";
