// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Document } from "../../shared/Document";

export type UserSetAvatarArgs = { avatar?: Document | undefined, };
