// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalBotPermissions } from "../../shared/ExternalBotPermissions";
import type { UserId } from "../../shared/UserId";

export type CommunityUpdateBotArgs = {
  bot_id: UserId;
  granted_permissions: ExternalBotPermissions;
};
