// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndex_ChitBalances_SuccessResult } from "./UserIndex_ChitBalances_SuccessResult";

export type UserIndex_ChitBalances_Response = { "Success": UserIndex_ChitBalances_SuccessResult };
