// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSPrincipal } from "../../shared/TSPrincipal";

export type ProposalsBotTopUpNeuronArgs = { governance_canister_id: TSPrincipal, amount: bigint, };
