// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectedGroupUpdates } from "../../shared/SelectedGroupUpdates";
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";

export type GroupSelectedUpdatesResponse = { "Success": SelectedGroupUpdates } | { "SuccessNoUpdates": TSBigIntWithDefault } | "CallerNotInGroup";
