// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuccessResult } from "./SuccessResult";

export type Response = { "kind": "Success" } & SuccessResult | { "kind": "AlreadyLifetimeDiamondMember" } | { "kind": "CurrencyNotSupported" } | { "kind": "PriceMismatch" } | { "kind": "PaymentAlreadyInProgress" } | { "kind": "UserNotFound" } | { "kind": "InsufficientFunds" } & bigint | { "kind": "TransferFailed" } & string | { "kind": "InternalError" } & string;
