// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { groupIndexRecommendedGroupsSuccessResult } from "./groupIndexRecommendedGroupsSuccessResult";

export type groupIndexRecommendedGroupsResponse = { "Success": groupIndexRecommendedGroupsSuccessResult };
