// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "../../shared/ChatId";

export type groupIndexRecommendedGroupsArgs = { count: number, exclusions: Array<ChatId>, };
