// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldTooLongResult } from "../../shared/FieldTooLongResult";
import type { FieldTooShortResult } from "../../shared/FieldTooShortResult";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";
import type { UserCreateGroupSuccessResult } from "./UserCreateGroupSuccessResult";

export type UserCreateGroupResponse = { "Success": UserCreateGroupSuccessResult } | { "NameTooShort": FieldTooShortResult } | { "NameTooLong": FieldTooLongResult } | "NameReserved" | { "DescriptionTooLong": FieldTooLongResult } | { "RulesTooShort": FieldTooShortResult } | { "RulesTooLong": FieldTooLongResult } | { "AvatarTooBig": FieldTooLongResult } | "AccessGateInvalid" | { "MaxGroupsCreated": TSNumberWithDefault } | "NameTaken" | "Throttled" | "UserSuspended" | "UnauthorizedToCreatePublicGroup" | "InternalError";
