// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeaderboardFilter } from "./LeaderboardFilter";

export type Args = { filter: LeaderboardFilter | null, count: number, };
