// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "../../shared/MessageIndex";
import type { TSBoolWithDefault } from "../../shared/TSBoolWithDefault";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type GroupEventsArgs = { thread_root_message_index?: MessageIndex | undefined, start_index: TSNumberWithDefault, ascending: TSBoolWithDefault, max_messages: TSNumberWithDefault, max_events: TSNumberWithDefault, latest_known_update?: bigint | undefined, };
