// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBytes } from "../../shared/TSBytes";

export type LocalUserIndexGroupAndCommunitySummaryUpdatesSummaryUpdatesArgs = { canister_id: TSBytes, is_community: boolean, invite_code?: bigint | undefined, updates_since?: bigint | undefined, };
