// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityUndeleteMessagesSuccessResult } from "./CommunityUndeleteMessagesSuccessResult";

export type CommunityUndeleteMessagesResponse = { "Success": CommunityUndeleteMessagesSuccessResult } | "MessageNotFound" | "GroupNotFound" | "UserNotInCommunity" | "UserNotInChannel" | "UserSuspended" | "CommunityFrozen" | "UserLapsed";
