// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "../../shared/ChatId";
import type { VerifiedCredentialGateArgs } from "../../shared/VerifiedCredentialGateArgs";

export type LocalUserIndexJoinGroupArgs = { chat_id: ChatId, invite_code?: bigint, verified_credential_args?: VerifiedCredentialGateArgs, correlation_id: bigint, };
