// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateCheckFailedReason } from "../../shared/GateCheckFailedReason";
import type { GroupCanisterGroupChatSummary } from "../../shared/GroupCanisterGroupChatSummary";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type LocalUserIndexJoinGroupResponse = { "Success": GroupCanisterGroupChatSummary } | "AlreadyInGroup" | { "AlreadyInGroupV2": GroupCanisterGroupChatSummary } | { "GateCheckFailed": GateCheckFailedReason } | "GroupNotFound" | "GroupNotPublic" | "NotInvited" | { "ParticipantLimitReached": TSNumberWithDefault } | "Blocked" | "UserSuspended" | "ChatFrozen" | { "InternalError": string };
