// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";
import type { TSBytes } from "../../shared/TSBytes";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type StorageBucketUploadChunkArgs = { file_id: bigint, hash: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], mime_type: string, 
/**
 * @default []
 */
accessors: Array<TSBytes>, chunk_index: TSNumberWithDefault, chunk_size: TSNumberWithDefault, total_size: TSBigIntWithDefault, bytes: TSBytes, expiry?: bigint | undefined, };
