// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBytes } from "../../shared/TSBytes";

export type StorageBucketUploadChunkArgs = { file_id: bigint, hash: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], mime_type: string, 
/**
 * @default []
 */
accessors: Array<TSBytes>, 
/**
 * @default 0
 */
chunk_index: number, 
/**
 * @default 0
 */
chunk_size: number, total_size: bigint, bytes: TSBytes, expiry?: bigint | undefined, };
