// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "../../shared/UserId";

export type CommunityCancelInvitesArgs = { channel_id?: bigint | undefined, 
/**
 * @default []
 */
user_ids: Array<UserId>, };
