// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";

export type UserTipMessageResponse = "Success" | "ChatNotFound" | "MessageNotFound" | "CannotTipSelf" | "NotAuthorized" | "TransferCannotBeZero" | "TransferNotToMessageSender" | { "TransferFailed": string } | "ChatFrozen" | "PinRequired" | { "PinIncorrect": TSBigIntWithDefault } | { "TooManyFailedPinAttempts": TSBigIntWithDefault } | "UserSuspended" | "UserLapsed" | { "Retrying": string } | { "InternalError": string };
