// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserWalletConfig } from "../UserWalletConfig";

export type UserConfigureWalletArgs = { config: UserWalletConfig, };
