// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "../../shared/CommunityId";
import type { groupIndexFreezeCommunitySuspensionDetails } from "./groupIndexFreezeCommunitySuspensionDetails";

export type groupIndexFreezeCommunityArgs = { community_id: CommunityId, reason?: string, suspend_members?: groupIndexFreezeCommunitySuspensionDetails, };
