// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "../../CommunityId";
import type { GroupIndex_FreezeCommunity_SuspensionDetails } from "./GroupIndex_FreezeCommunity_SuspensionDetails";

export type GroupIndex_FreezeCommunity_Args = { community_id: CommunityId, reason?: string, suspend_members?: GroupIndex_FreezeCommunity_SuspensionDetails, };
