// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventWrapperGroupFrozen } from "../../EventWrapperGroupFrozen";

export type GroupIndex_FreezeCommunity_Response = { "Success": EventWrapperGroupFrozen } | "CommunityAlreadyFrozen" | "CommunityNotFound" | "NotAuthorized" | { "InternalError": string };
