// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageBucketDeleteFilesDeleteFileFailureReason } from "./StorageBucketDeleteFilesDeleteFileFailureReason";

export type StorageBucketDeleteFilesDeleteFileFailure = { file_id: bigint, reason: StorageBucketDeleteFilesDeleteFileFailureReason, };
