[package]
name = "daily_puzzle_canister_impl"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
bridges = { path = "../../../libraries/bridges" }
candid = { workspace = true }
canister_api_macros = { path = "../../../libraries/canister_api_macros" }
canister_client = { path = "../../../libraries/canister_client" }
canister_logger = { path = "../../../libraries/canister_logger" }
canister_state_macros = { path = "../../../libraries/canister_state_macros" }
canister_tracing_macros = { path = "../../../libraries/canister_tracing_macros" }
constants = { path = "../../../libraries/constants" }
daily_puzzle_canister = { path = "../api" }
futures = { workspace = true }
git_commit_id = { path = "../../../libraries/git_commit_id" }
http_request = { path = "../../../libraries/http_request" }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-stable-structures = { workspace = true }
light_up = { path = "../../../libraries/light_up" }
loopy = { path = "../../../libraries/loopy" }
local_user_index_canister = { path = "../../local_user_index/api" }
local_user_index_canister_c2c_client = { path = "../../local_user_index/c2c_client" }
msgpack = { path = "../../../libraries/msgpack" }
oc_error_codes = { path = "../../../libraries/error_codes" }
rand = { workspace = true }
registry_canister = { path = "../../registry/api" }
serde = { workspace = true }
slant = { path = "../../../libraries/slant" }
stable_memory = { path = "../../../libraries/stable_memory" }
tents = { path = "../../../libraries/tents" }
tracing = { workspace = true }
unruly = { path = "../../../libraries/unruly" }
types = { path = "../../../libraries/types" }
utils = { path = "../../../libraries/utils" }
