// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlashCommandPermissions } from "../../shared/SlashCommandPermissions";
import type { UserId } from "../../shared/UserId";

export type GroupAddBotArgs = { bot_id: UserId, granted_permissions: SlashCommandPermissions, };
