// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoCallParticipants } from "../../shared/VideoCallParticipants";

export type GroupVideoCallParticipantsResponse = { "Success": VideoCallParticipants } | "VideoCallNotFound" | "CallerNotInGroup";
