// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBoolWithDefault } from "../../shared/TSBoolWithDefault";

export type CommunitySetMemberDisplayNameArgs = { display_name?: string | undefined, new_achievement: TSBoolWithDefault, };
