// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "../shared/TSBigIntWithDefault";
import type { TSBoolWithDefault } from "../shared/TSBoolWithDefault";
import type { TSBytes } from "../shared/TSBytes";
import type { TSNumberWithDefault } from "../shared/TSNumberWithDefault";

export type RegistryTokenDetails = { ledger_canister_id: TSBytes, name: string, symbol: string, decimals: TSNumberWithDefault, fee: TSBigIntWithDefault, logo: string, logo_id?: bigint | undefined, info_url: string, how_to_buy_url: string, transaction_url_format: string, 
/**
 * @default []
 */
supported_standards: Array<string>, added: TSBigIntWithDefault, enabled: TSBoolWithDefault, last_updated: TSBigIntWithDefault, };
