// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegistryPayment } from "./RegistryPayment";
import type { TSPrincipal } from "../shared/TSPrincipal";

export type RegistryTokenDetails = { ledger_canister_id: TSPrincipal, name: string, symbol: string, decimals: number, fee: bigint, logo: string, logo_id?: bigint, info_url: string, how_to_buy_url: string, transaction_url_format: string, supported_standards: Array<string>, added: bigint, enabled: boolean, last_updated: bigint, payments: Array<RegistryPayment>, };
