// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBytes } from "../shared/TSBytes";

export type RegistryNervousSystemSummary = { root_canister_id: TSBytes, governance_canister_id: TSBytes, ledger_canister_id: TSBytes, index_canister_id: TSBytes, 
/**
 * @default false
 */
is_nns: boolean, proposal_rejection_fee: bigint, 
/**
 * @default false
 */
submitting_proposals_enabled: boolean, };
