// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "../shared/UserId";

export type RegistryPayment = { amount: bigint, block_index: bigint, timestamp: bigint, user_id: UserId, };
