// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityMember } from "../../shared/CommunityMember";
import type { EventIndex } from "../../shared/EventIndex";
import type { UserGroupDetails } from "../../shared/UserGroupDetails";
import type { UserId } from "../../shared/UserId";
import type { VersionedRules } from "../../shared/VersionedRules";

export type CommunitySelectedInitialSuccessResult = { timestamp: bigint, last_updated: bigint, 
/**
 * @default 0
 */
latest_event_index: EventIndex, 
/**
 * @default []
 */
members: Array<CommunityMember>, 
/**
 * @default []
 */
blocked_users: Array<UserId>, 
/**
 * @default []
 */
invited_users: Array<UserId>, chat_rules: VersionedRules, 
/**
 * @default []
 */
user_groups: Array<UserGroupDetails>, 
/**
 * @default []
 */
referrals: Array<UserId>, };
