import type { IDL } from "@dfinity/candid";
import UserService, {
  UpdatesArgs,
  UpdatesResponse,
  ChatSummary,
  GroupChatSummary,
  DirectChatSummary,
  Message,
  UserId,
  ReplyContext,
  MessageContent,
  FileContent,
  TextContent,
  MediaContent,
  CyclesContent,
  TimestampMillis,
  BlobReference,
  MessagesArgs,
  MessagesResponse,
  MessagesSuccess,
} from "./types";
export {
  UserService,
  UpdatesArgs as ApiUpdatesArgs,
  UpdatesResponse as ApiUpdatesResponse,
  ChatSummary as ApiChatSummary,
  GroupChatSummary as ApiGroupChatSummary,
  DirectChatSummary as ApiDirectChatSummary,
  Message as ApiMessage,
  UserId as ApiUserId,
  ReplyContext as ApiReplyContext,
  MessageContent as ApiMessageContent,
  FileContent as ApiFileContent,
  TextContent as ApiTextContent,
  MediaContent as ApiMediaContent,
  CyclesContent as ApiCyclesContent,
  TimestampMillis as ApiTimestampMillis,
  BlobReference as ApiBlobReference,
  MessagesArgs as ApiMessageArgs,
  MessagesResponse as ApiMessagesResponse,
  MessagesSuccess as ApiMessagesSuccess,
};

declare const idlFactory: IDL.InterfaceFactory;
export default idlFactory;
