// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupIndexExploreGroupsSuccessResult } from "./GroupIndexExploreGroupsSuccessResult";

export type GroupIndexExploreGroupsResponse = { "Success": GroupIndexExploreGroupsSuccessResult } | { "TermTooShort": number } | { "TermTooLong": number } | "InvalidTerm";
