// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { groupIndexExploreGroupsSuccessResult } from "./groupIndexExploreGroupsSuccessResult";

export type groupIndexExploreGroupsResponse = { "Success": groupIndexExploreGroupsSuccessResult } | { "TermTooShort": number } | { "TermTooLong": number } | "InvalidTerm";
