// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupIndex_ExploreGroups_SuccessResult } from "./GroupIndex_ExploreGroups_SuccessResult";

export type GroupIndex_ExploreGroups_Response = { "Success": GroupIndex_ExploreGroups_SuccessResult } | { "TermTooShort": number } | { "TermTooLong": number } | "InvalidTerm";
