// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupMatch } from "../../GroupMatch";

export type GroupIndex_ExploreGroups_SuccessResult = { matches: Array<GroupMatch>, total: number, };
