// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessGate } from "../../shared/AccessGate";
import type { AccessGateConfig } from "../../shared/AccessGateConfig";
import type { Document } from "../../shared/Document";
import type { GroupPermissions } from "../../shared/GroupPermissions";
import type { GroupSubtype } from "../../shared/GroupSubtype";
import type { Rules } from "../../shared/Rules";

export type CommunityCreateChannelArgs = { is_public: boolean, name: string, description: string, rules: Rules, subtype?: GroupSubtype, avatar?: Document, history_visible_to_new_joiners: boolean, messages_visible_to_non_members?: boolean, permissions_v2?: GroupPermissions, events_ttl?: bigint, gate?: AccessGate, gate_config?: AccessGateConfig, external_url?: string, };
