// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "../../ChatId";

export type GroupIndex_AddHotGroupExclusion_Args = { chat_id: ChatId, };
