// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserClaimDailyChitSuccessResult = { 
/**
 * @default 0
 */
chit_earned: number, 
/**
 * @default 0
 */
chit_balance: number, 
/**
 * @default 0
 */
streak: number, next_claim: bigint, };
