// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserClaimDailyChitSuccessResult = { chit_earned: number, chit_balance: number, streak: number, max_streak: number, next_claim: bigint, };
