// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { YearAndMonth } from "./YearAndMonth";

export type LeaderboardFilter = { "Month": YearAndMonth } | "CurrentMonth";
