// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuccessResult } from "../../shared/SuccessResult";

export type GroupGenerateBotApiKeyResponse = { "Success": SuccessResult } | "BotNotFound" | "ChatFrozen" | "NotAuthorized";
