// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiamondMembershipSubscription } from "../../DiamondMembershipSubscription";

export type UserIndex_UpdateDiamondMembershipSubscription_Args = { pay_in_chat: boolean | null, subscription: DiamondMembershipSubscription | null, };
