// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserIndexBotSendMessageSuccessResult } from "./LocalUserIndexBotSendMessageSuccessResult";

export type LocalUserIndexBotSendMessageResponse = { "Success": LocalUserIndexBotSendMessageSuccessResult } | { "FailedAuthentication": string } | { "InvalidRequest": string } | "NotAuthorized" | "Frozen" | "ThreadNotFound" | "MessageAlreadyFinalised" | { "C2CError": [number, string] };
