import { IDL } from "@dfinity/candid"

export const Notification = IDL.Variant({
  'GroupReactionAdded' : IDL.Record({
    'added_by_name' : IDL.Text,
    'message_event_index' : IDL.Nat32,
    'added_by' : IDL.Principal,
    'chat_id' : IDL.Principal,
    'thread_root_message_index' : IDL.Opt(IDL.Nat32),
    'group_name' : IDL.Text,
    'reaction' : IDL.Text,
    'message_index' : IDL.Nat32,
  }),
  'DirectMessage' : IDL.Record({
    'thumbnail' : IDL.Opt(IDL.Text),
    'sender' : IDL.Principal,
    'sender_name' : IDL.Text,
    'message_text' : IDL.Opt(IDL.Text),
    'message_type' : IDL.Text,
    'event_index' : IDL.Nat32,
    'thread_root_message_index' : IDL.Opt(IDL.Nat32),
    'message_index' : IDL.Nat32,
  }),
  'ChannelReactionAdded' : IDL.Record({
    'channel_id' : IDL.Nat,
    'community_id' : IDL.Principal,
    'added_by_name' : IDL.Text,
    'message_event_index' : IDL.Nat32,
    'added_by' : IDL.Principal,
    'channel_name' : IDL.Text,
    'community_name' : IDL.Text,
    'thread_root_message_index' : IDL.Opt(IDL.Nat32),
    'reaction' : IDL.Text,
    'message_index' : IDL.Nat32,
  }),
  'DirectReactionAdded' : IDL.Record({
    'username' : IDL.Text,
    'message_event_index' : IDL.Nat32,
    'them' : IDL.Principal,
    'thread_root_message_index' : IDL.Opt(IDL.Nat32),
    'reaction' : IDL.Text,
    'message_index' : IDL.Nat32,
  }),
  'GroupMessage' : IDL.Record({
    'thumbnail' : IDL.Opt(IDL.Text),
    'sender' : IDL.Principal,
    'sender_name' : IDL.Text,
    'message_text' : IDL.Opt(IDL.Text),
    'message_type' : IDL.Text,
    'chat_id' : IDL.Principal,
    'event_index' : IDL.Nat32,
    'thread_root_message_index' : IDL.Opt(IDL.Nat32),
    'group_name' : IDL.Text,
    'message_index' : IDL.Nat32,
  }),
  'AddedToGroup' : IDL.Record({
    'added_by_name' : IDL.Text,
    'added_by' : IDL.Principal,
    'chat_id' : IDL.Principal,
    'group_name' : IDL.Text,
  }),
  'AddedToChannel' : IDL.Record({
    'channel_id' : IDL.Nat,
    'community_id' : IDL.Principal,
    'added_by_name' : IDL.Text,
    'added_by' : IDL.Principal,
    'channel_name' : IDL.Text,
    'community_name' : IDL.Text,
  }),
  'ChannelMessage' : IDL.Record({
    'channel_id' : IDL.Nat,
    'community_id' : IDL.Principal,
    'thumbnail' : IDL.Opt(IDL.Text),
    'sender' : IDL.Principal,
    'channel_name' : IDL.Text,
    'community_name' : IDL.Text,
    'sender_name' : IDL.Text,
    'message_text' : IDL.Opt(IDL.Text),
    'message_type' : IDL.Text,
    'event_index' : IDL.Nat32,
    'thread_root_message_index' : IDL.Opt(IDL.Nat32),
    'message_index' : IDL.Nat32,
  }),
});

