// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndex_PlatformOperators_SuccessResult } from "./UserIndex_PlatformOperators_SuccessResult";

export type UserIndex_PlatformOperators_Response = { "Success": UserIndex_PlatformOperators_SuccessResult };
