// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectedGroupUpdates } from "../../shared/SelectedGroupUpdates";

export type CommunitySelectedChannelUpdatesResponse = { "Success": SelectedGroupUpdates } | { "SuccessNoUpdates": bigint } | "PrivateCommunity" | "ChannelNotFound" | "PrivateChannel";
