// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "./MessageIndex";

export type ChannelLatestMessageIndex = { channel_id: bigint, latest_message_index: MessageIndex | null, };
