// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Achievement } from "./Achievement";

export type ChitEarnedReason = "DailyClaim" | { "Achievement": Achievement } | "MemeContestWinner";
