// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChitEarnedReason } from "./ChitEarnedReason";

export type ChitEarned = { amount: number, timestamp: bigint, reason: ChitEarnedReason, };
