// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessGate } from "./AccessGate";
import type { ChatMetrics } from "./ChatMetrics";
import type { EventIndex } from "./EventIndex";
import type { EventWrapper } from "./EventWrapper";
import type { GroupMembershipUpdates } from "./GroupMembershipUpdates";
import type { GroupPermissions } from "./GroupPermissions";
import type { GroupSubtype } from "./GroupSubtype";
import type { Message } from "./Message";
import type { MessageIndex } from "./MessageIndex";
import type { OptionUpdate } from "./OptionUpdate";
import type { VideoCall } from "./VideoCall";

export type CommunityCanisterChannelSummaryUpdates = { channel_id: bigint, last_updated: bigint, name: string | null, description: string | null, subtype: OptionUpdate<GroupSubtype>, avatar_id: OptionUpdate<bigint>, is_public: boolean | null, messages_visible_to_non_members: boolean | null, latest_message: EventWrapper<Message> | null, latest_message_sender_display_name: string | null, latest_event_index: EventIndex | null, latest_message_index: MessageIndex | null, member_count: number | null, permissions_v2: GroupPermissions | null, updated_events: Array<[MessageIndex | null, EventIndex, bigint]>, metrics: ChatMetrics | null, date_last_pinned: bigint | null, events_ttl: OptionUpdate<bigint>, events_ttl_last_updated: bigint | null, gate: OptionUpdate<AccessGate>, membership: GroupMembershipUpdates | null, video_call_in_progress: OptionUpdate<VideoCall>, };
