// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoAccount } from "./CryptoAccount";
import type { Cryptocurrency } from "./Cryptocurrency";
import type { Principal } from "./Principal";
import type { Tokens } from "./Tokens";

export type CompletedCryptoTransaction = { ledger: Principal, token: Cryptocurrency, amount: Tokens, fee: Tokens, from: CryptoAccount, to: CryptoAccount, memo: bigint, created: bigint, transaction_hash: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], block_index: bigint, };
