// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "./ChatId";
import type { ChatMetrics } from "./ChatMetrics";
import type { EventIndex } from "./EventIndex";
import type { EventWrapper } from "./EventWrapper";
import type { Message } from "./Message";
import type { MessageIndex } from "./MessageIndex";
import type { OptionUpdate } from "./OptionUpdate";
import type { VideoCall } from "./VideoCall";

export type DirectChatSummaryUpdates = { chat_id: ChatId, last_updated: bigint, latest_message: EventWrapper<Message> | null, latest_event_index: EventIndex | null, latest_message_index: MessageIndex | null, read_by_me_up_to: MessageIndex | null, read_by_them_up_to: MessageIndex | null, notifications_muted: boolean | null, updated_events: Array<[EventIndex, bigint]>, metrics: ChatMetrics | null, my_metrics: ChatMetrics | null, archived: boolean | null, events_ttl: OptionUpdate<bigint>, events_ttl_last_updated: bigint | null, video_call_in_progress: OptionUpdate<VideoCall>, };
