// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoAccount } from "./CryptoAccount";
import type { Cryptocurrency } from "./Cryptocurrency";
import type { Principal } from "./Principal";

export type FailedCryptoTransaction = { ledger: Principal, token: Cryptocurrency, amount: bigint, fee: bigint, from: CryptoAccount, to: CryptoAccount, memo: Array<number> | null, created: bigint, error_message: string, };
