// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileMetaData } from "./FileMetaData";

export type FileRemoved = { file_id: bigint, meta_data: FileMetaData, };
