// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileStatusUploading = { created: bigint, index_sync_complete: boolean, mime_type: string, size: bigint, chunk_size: number, chunks_remaining: Array<number>, };
