// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferFromErrorJS } from "./TransferFromErrorJS";

export type GateCheckFailedReason = "NotDiamondMember" | "NotLifetimeDiamondMember" | "NoUniquePersonProof" | "NoSnsNeuronsFound" | "NoSnsNeuronsWithRequiredStakeFound" | "NoSnsNeuronsWithRequiredDissolveDelayFound" | { "PaymentFailed": TransferFromErrorJS } | { "InsufficientBalance": bigint } | { "FailedVerifiedCredentialCheck": string } | "Locked";
