// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

export type GroupVisibilityChanged = { public: boolean | null, messages_visible_to_non_members: boolean | null, changed_by: UserId, };
