// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "./MessageIndex";

export type Mention = { timestamp: bigint, thread_root_message_index: MessageIndex | null, message_index: MessageIndex, };
