// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomPermission } from "./CustomPermission";
import type { GroupPermissionRole } from "./GroupPermissionRole";

export type MessagePermissions = { default: GroupPermissionRole, text: GroupPermissionRole | null, image: GroupPermissionRole | null, video: GroupPermissionRole | null, audio: GroupPermissionRole | null, file: GroupPermissionRole | null, poll: GroupPermissionRole | null, crypto: GroupPermissionRole | null, giphy: GroupPermissionRole | null, prize: GroupPermissionRole | null, p2p_swap: GroupPermissionRole | null, video_call: GroupPermissionRole | null, custom: Array<CustomPermission>, };
