// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomPermission } from "./CustomPermission";
import type { GroupPermissionRole } from "./GroupPermissionRole";
import type { OptionUpdate } from "./OptionUpdate";

export type OptionalMessagePermissions = { default: GroupPermissionRole | null, text: OptionUpdate<GroupPermissionRole>, image: OptionUpdate<GroupPermissionRole>, video: OptionUpdate<GroupPermissionRole>, audio: OptionUpdate<GroupPermissionRole>, file: OptionUpdate<GroupPermissionRole>, poll: OptionUpdate<GroupPermissionRole>, crypto: OptionUpdate<GroupPermissionRole>, giphy: OptionUpdate<GroupPermissionRole>, prize: OptionUpdate<GroupPermissionRole>, p2p_swap: OptionUpdate<GroupPermissionRole>, video_call: OptionUpdate<GroupPermissionRole>, custom_updated: Array<CustomPermission>, custom_deleted: Array<string>, };
