// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Principal } from "./Principal";

export type PaymentGate = { ledger_canister_id: Principal, amount: bigint, fee: bigint, };
