// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Principal } from "./Principal";
import type { VerifiedCredentialArgumentValue } from "./VerifiedCredentialArgumentValue";

export type VerifiedCredentialGate = { issuer_canister_id: Principal, issuer_origin: string, credential_type: string, credential_name: string, credential_arguments: { [key: string]: VerifiedCredentialArgumentValue }, };
