// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndex_ReferralLeaderboard_ReferralStats } from "./UserIndex_ReferralLeaderboard_ReferralStats";

export type UserIndex_ReferralLeaderboard_MonthSuccessResult = { year: number, month: number, results: Array<UserIndex_ReferralLeaderboard_ReferralStats>, };
