// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndex_ReferralLeaderboard_YearAndMonth } from "./UserIndex_ReferralLeaderboard_YearAndMonth";

export type UserIndex_ReferralLeaderboard_LeaderboardFilter = { "Month": UserIndex_ReferralLeaderboard_YearAndMonth } | "CurrentMonth";
