// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentUserSummary } from "../../shared/CurrentUserSummary";
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";
import type { UserId } from "../../shared/UserId";
import type { UserSummaryV2 } from "../../shared/UserSummaryV2";

export type UserIndexUsersResult = { 
/**
 * @default []
 */
users: Array<UserSummaryV2>, current_user?: CurrentUserSummary | undefined, 
/**
 * @default []
 */
deleted: Array<UserId>, timestamp: TSBigIntWithDefault, };
