// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserGroup } from "./UserGroup";

export type Args = { user_groups: Array<UserGroup>, users_suspended_since: bigint | null, };
