// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserChatInList } from "../UserChatInList";

export type UserPinChatArgs = { chat: UserChatInList, };
