// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "../../shared/CommunityId";
import type { UserCommunitySummary } from "../UserCommunitySummary";
import type { UserCommunitySummaryUpdates } from "../UserCommunitySummaryUpdates";

export type UserUpdatesCommunitiesUpdates = { 
/**
 * @default []
 */
added: Array<UserCommunitySummary>, 
/**
 * @default []
 */
updated: Array<UserCommunitySummaryUpdates>, 
/**
 * @default []
 */
removed: Array<CommunityId>, };
