// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "../../shared/ChatId";

export type GroupIndexRecommendedGroupsArgs = { 
/**
 * @default 0
 */
count: number, 
/**
 * @default []
 */
exclusions: Array<ChatId>, };
