// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposalsBotCommonProposalToSubmitAction } from "./ProposalsBotCommonProposalToSubmitAction";

export type ProposalsBotCommonProposalToSubmit = { title: string, summary: string, url: string, action: ProposalsBotCommonProposalToSubmitAction, };
