// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalTS } from "../../shared/PrincipalTS";
import type { ProposalsBotCommonCanisterInstallMode } from "./ProposalsBotCommonCanisterInstallMode";

export type ProposalsBotCommonUpgradeSnsControlledCanister = { canister_id: PrincipalTS, new_canister_wasm: Array<number>, mode: ProposalsBotCommonCanisterInstallMode, };
