// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposalsBotCommonExecuteGenericNervousSystemFunction } from "./ProposalsBotCommonExecuteGenericNervousSystemFunction";
import type { ProposalsBotCommonTransferSnsTreasuryFunds } from "./ProposalsBotCommonTransferSnsTreasuryFunds";
import type { ProposalsBotCommonUpgradeSnsControlledCanister } from "./ProposalsBotCommonUpgradeSnsControlledCanister";

export type ProposalsBotCommonProposalToSubmitAction = "Motion" | { "TransferSnsTreasuryFunds": ProposalsBotCommonTransferSnsTreasuryFunds } | "UpgradeSnsToNextVersion" | { "UpgradeSnsControlledCanister": ProposalsBotCommonUpgradeSnsControlledCanister } | { "ExecuteGenericNervousSystemFunction": ProposalsBotCommonExecuteGenericNervousSystemFunction };
