// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposalsBotCommonCanisterInstallMode } from "./ProposalsBotCommonCanisterInstallMode";
import type { TSBytes } from "../../shared/TSBytes";

export type ProposalsBotCommonUpgradeSnsControlledCanister = { canister_id: TSBytes, new_canister_wasm: TSBytes, mode: ProposalsBotCommonCanisterInstallMode, };
