// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PushEventResult } from "../../shared/PushEventResult";

export type CommunityPinMessageResponse = { "Success": PushEventResult } | "CommunityFrozen" | "UserNotInCommunity" | "UserSuspended" | "ChannelNotFound" | "UserNotInChannel" | "MessageNotFound" | "NotAuthorized" | "NoChange" | "UserLapsed";
