// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommunityApiKeyResponse = { "Success": string } | "NotAuthorized" | "NotFound" | "ChannelNotFound";
