// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "../../shared/ChannelId";
import type { UserId } from "../../shared/UserId";

export type CommunityApiKeyArgs = { bot_id: UserId, channel_id?: ChannelId, };
