// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Result } from "./Result";

export type Response = { "kind": "Success" } & Result;
