// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthToken } from "../../shared/AuthToken";
import type { ChannelId } from "../../shared/ChannelId";

export type LocalUserIndexBotDeleteChannelArgs = { channel_id: ChannelId, auth_token: AuthToken, };
