// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalUserIndexBotDeleteChannelResponse = "Success" | "ChannelNotFound" | { "FailedAuthentication": string } | { "InvalidRequest": string } | "NotAuthorized" | "Frozen" | { "C2CError": [number, string] };
