// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "../../shared/MessageId";

export type GroupClaimPrizeArgs = { message_id: MessageId, correlation_id: bigint, };
