// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "../../shared/MessageIndex";

export type GroupEventsWindowArgs = { thread_root_message_index?: MessageIndex | undefined, 
/**
 * @default 0
 */
mid_point: MessageIndex, 
/**
 * @default 0
 */
max_messages: number, 
/**
 * @default 0
 */
max_events: number, latest_known_update?: bigint | undefined, };
