// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "../../shared/MessageId";
import type { MessageIndex } from "../../shared/MessageIndex";
import type { PinNumberWrapper } from "../../shared/PinNumberWrapper";
import type { UserId } from "../../shared/UserId";

export type UserAcceptP2pSwapArgs = { user_id: UserId, thread_root_message_index?: MessageIndex | undefined, message_id: MessageId, pin?: PinNumberWrapper | undefined, };
