// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserSwapTokensICPSwapArgs } from "./UserSwapTokensICPSwapArgs";

export type UserSwapTokensExchangeArgs = { "ICPSwap": UserSwapTokensICPSwapArgs } | { "Sonic": UserSwapTokensICPSwapArgs } | { "KongSwap": UserSwapTokensICPSwapArgs };
