// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "../../shared/CommunityId";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type GroupIndexSetCommunityModerationFlagsArgs = { community_id: CommunityId, flags: TSNumberWithDefault, };
