// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletedCryptoTransaction } from "../../shared/CompletedCryptoTransaction";
import type { Cryptocurrency } from "../../shared/Cryptocurrency";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";
import type { UserSendMessageWithTransferToChannelSuccessResult } from "./UserSendMessageWithTransferToChannelSuccessResult";

export type UserSendMessageWithTransferToChannelResponse = { "Success": UserSendMessageWithTransferToChannelSuccessResult } | { "TextTooLong": TSNumberWithDefault } | "RecipientBlocked" | { "UserNotInCommunity": CompletedCryptoTransaction | null } | { "UserNotInChannel": CompletedCryptoTransaction } | { "ChannelNotFound": CompletedCryptoTransaction } | { "CryptocurrencyNotSupported": Cryptocurrency } | { "InvalidRequest": string } | { "TransferFailed": string } | "TransferCannotBeZero" | "TransferCannotBeToSelf" | { "P2PSwapSetUpFailed": string } | "UserSuspended" | "UserLapsed" | "CommunityFrozen" | "RulesNotAccepted" | "CommunityRulesNotAccepted" | { "Retrying": [string, CompletedCryptoTransaction] } | "PinRequired" | { "PinIncorrect": bigint } | { "TooManyFailedPinAttempts": bigint } | { "InternalError": string };
