// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserSummary } from "../../shared/UserSummary";

export type userIndexSearchResult = { users: Array<UserSummary>, timestamp: bigint, };
