// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndex_Search_Result } from "./UserIndex_Search_Result";

export type UserIndex_Search_Response = { "Success": UserIndex_Search_Result };
