// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotPermissions } from "../../shared/BotPermissions";
import type { UserId } from "../../shared/UserId";

export type GroupUpdateBotArgs = { bot_id: UserId, granted_permissions: BotPermissions, };
