// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndex_PlatformModerators_SuccessResult } from "./UserIndex_PlatformModerators_SuccessResult";

export type UserIndex_PlatformModerators_Response = { "Success": UserIndex_PlatformModerators_SuccessResult };
