// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Response = { "kind": "Success" } | { "kind": "Unauthorized" } | { "kind": "UserNotFound" } | { "kind": "DisplayNameInvalid" } | { "kind": "DisplayNameTooShort", "value": number } | { "kind": "DisplayNameTooLong", "value": number };
