// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingCryptoTransactionICRC2 } from "../../shared/PendingCryptoTransactionICRC2";
import type { ProposalsBotProposalToSubmit } from "../ProposalsBotProposalToSubmit";
import type { TSPrincipal } from "../../shared/TSPrincipal";

export type ProposalsBotSubmitProposalArgs = { governance_canister_id: TSPrincipal, proposal: ProposalsBotProposalToSubmit, transaction: PendingCryptoTransactionICRC2, };
