// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageIndexProjectedAllowance } from "../StorageIndexProjectedAllowance";
import type { TSBytes } from "../../shared/TSBytes";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type StorageIndexAllocationBucketSuccessResult = { canister_id: TSBytes, file_id: bigint, chunk_size: TSNumberWithDefault, byte_limit: bigint, bytes_used: bigint, bytes_used_after_upload: bigint, projected_allowance: StorageIndexProjectedAllowance, };
