// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageIndexAllocationBucketSuccessResult } from "./StorageIndexAllocationBucketSuccessResult";
import type { StorageIndexProjectedAllowance } from "../StorageIndexProjectedAllowance";

export type StorageIndexAllocationBucketResponse = { "Success": StorageIndexAllocationBucketSuccessResult } | { "AllowanceExceeded": StorageIndexProjectedAllowance } | "UserNotFound" | "BucketUnavailable";
