// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessagesResponse } from "../../shared/MessagesResponse";

export type GroupMessagesByMessageIndexResponse = { "Success": MessagesResponse } | "CallerNotInGroup" | "ThreadMessageNotFound" | "UserSuspended" | "UserLapsed" | { "ReplicaNotUpToDateV2": bigint };
