// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotMatch } from "../../shared/BotMatch";

export type UserIndexExploreBotsSuccessResult = { matches: Array<BotMatch>, total: number, };
