// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserIndexExternalAchievementsExternalAchievement = { id: number, name: string, url: string, chit_reward: number, expires: bigint, budget_exhausted: boolean, };
