// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndexExternalAchievementsSuccessResult } from "./UserIndexExternalAchievementsSuccessResult";

export type UserIndexExternalAchievementsResponse = { "Success": UserIndexExternalAchievementsSuccessResult } | "SuccessNoUpdates";
