// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommunityBlockUserResponse = "Success" | "UserNotInCommunity" | "CannotBlockSelf" | "CannotBlockUser" | "CommunityNotPublic" | "NotAuthorized" | "TargetUserNotInCommunity" | "UserSuspended" | "CommunityFrozen" | { "InternalError": string } | "UserLapsed";
