// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunitySelectedChannelInitialSuccessResult } from "./CommunitySelectedChannelInitialSuccessResult";

export type CommunitySelectedChannelInitialResponse = { "Success": CommunitySelectedChannelInitialSuccessResult } | "PrivateCommunity" | "ChannelNotFound" | "PrivateChannel";
