// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { userIndexDiamondMembershipFeesDiamondMembershipFees } from "./userIndexDiamondMembershipFeesDiamondMembershipFees";

export type userIndexDiamondMembershipFeesResponse = { "Success": Array<userIndexDiamondMembershipFeesDiamondMembershipFees> };
