// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserMarkReadChatMessagesRead } from "./UserMarkReadChatMessagesRead";
import type { UserMarkReadCommunityMessagesRead } from "./UserMarkReadCommunityMessagesRead";

export type UserMarkReadArgs = { 
/**
 * @default []
 */
messages_read: Array<UserMarkReadChatMessagesRead>, 
/**
 * @default []
 */
community_messages_read: Array<UserMarkReadCommunityMessagesRead>, };
