// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "../../shared/ChatId";
import type { MessageIndex } from "../../shared/MessageIndex";
import type { UserMarkReadThreadRead } from "./UserMarkReadThreadRead";

export type UserMarkReadChatMessagesRead = { chat_id: ChatId, read_up_to?: MessageIndex | undefined, threads: Array<UserMarkReadThreadRead>, date_read_pinned?: bigint | undefined, };
