// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "../../shared/MessageIndex";

export type UserMarkReadThreadRead = { 
/**
 * @default 0
 */
root_message_index: MessageIndex, 
/**
 * @default 0
 */
read_up_to: MessageIndex, };
