// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityDeletedMessageSuccessResult } from "./CommunityDeletedMessageSuccessResult";

export type CommunityDeletedMessageResponse = { "Success": CommunityDeletedMessageSuccessResult } | "UserNotInCommunity" | "ChannelNotFound" | "UserNotInChannel" | "NotAuthorized" | "MessageNotFound" | "MessageHardDeleted";
