import type { IDL } from "@dfinity/candid";
import {
    _SERVICE,
    UpdatesArgs,
    UpdatesResponse,
    ChatSummary,
    GroupChatSummary,
    DirectChatSummary,
    Message,
    UserId,
    ReplyContext,
    MessageContent,
    FileContent,
    TextContent,
    MediaContent,
    CyclesContent,
    TimestampMillis,
    BlobReference,
    Participant,
    UpdatedChatSummary,
    EventIndex,
    EventWrapper,
    EventsByIndexArgs,
    EventsByIndexResponse,
    EventsResponse,
    EventsSuccessResult,
    EventsArgs,
} from "./types";
export {
    _SERVICE as UserService,
    UpdatesArgs as ApiUpdatesArgs,
    UpdatesResponse as ApiUpdatesResponse,
    ChatSummary as ApiChatSummary,
    GroupChatSummary as ApiGroupChatSummary,
    DirectChatSummary as ApiDirectChatSummary,
    Message as ApiMessage,
    UserId as ApiUserId,
    ReplyContext as ApiReplyContext,
    MessageContent as ApiMessageContent,
    FileContent as ApiFileContent,
    TextContent as ApiTextContent,
    MediaContent as ApiMediaContent,
    CyclesContent as ApiCyclesContent,
    TimestampMillis as ApiTimestampMillis,
    BlobReference as ApiBlobReference,
    Participant as ApiParticipant,
    UpdatedChatSummary as ApiUpdatedChatSummary,
    EventIndex as ApiEventIndex,
    EventWrapper as ApiEventWrapper,
    EventsByIndexArgs as ApiEventsByIndexArgs,
    EventsByIndexResponse as ApiEventsByIndexResponse,
    EventsResponse as ApiEventsResponse,
    EventsSuccessResult as ApiEventsSuccessResult,
    EventsArgs as ApiEventsArgs,
};

declare const idlFactory: IDL.InterfaceFactory;
export default idlFactory;
