// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessagesResponse } from "../../shared/MessagesResponse";
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";

export type UserMessagesByMessageIndexResponse = { "Success": MessagesResponse } | "ChatNotFound" | "ThreadMessageNotFound" | { "ReplicaNotUpToDateV2": TSBigIntWithDefault };
