// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserIndex_CheckUsername_Response = "Success" | "UsernameTaken" | "UsernameInvalid" | { "UsernameTooShort": number } | { "UsernameTooLong": number };
