// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SwapStatusError } from "../../shared/SwapStatusError";

export type CommunityCancelP2pSwapResponse = "Success" | { "StatusError": SwapStatusError } | "SwapNotFound" | "ChannelNotFound" | "UserNotInCommunity" | "UserNotInChannel" | "ChatFrozen";
