// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiamondMembershipFeesByDuration = { one_month: bigint, three_months: bigint, one_year: bigint, lifetime: bigint, };
