// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoAccountNNS } from "./CryptoAccountNNS";
import type { Cryptocurrency } from "./Cryptocurrency";
import type { Principal } from "./Principal";
import type { Tokens } from "./Tokens";

export type FailedCryptoTransactionNNS = { ledger: Principal, token: Cryptocurrency, amount: Tokens, fee: Tokens, from: CryptoAccountNNS, to: CryptoAccountNNS, memo: bigint, created: bigint, transaction_hash: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], error_message: string, };
