// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioContent } from "./AudioContent";
import type { CryptoContent } from "./CryptoContent";
import type { CustomContent } from "./CustomContent";
import type { DeletedBy } from "./DeletedBy";
import type { FileContent } from "./FileContent";
import type { GiphyContent } from "./GiphyContent";
import type { ImageContent } from "./ImageContent";
import type { MessageReminderContent } from "./MessageReminderContent";
import type { MessageReminderCreatedContent } from "./MessageReminderCreatedContent";
import type { P2PSwapContent } from "./P2PSwapContent";
import type { PollContent } from "./PollContent";
import type { PrizeContent } from "./PrizeContent";
import type { PrizeWinnerContent } from "./PrizeWinnerContent";
import type { ProposalContent } from "./ProposalContent";
import type { ReportedMessage } from "./ReportedMessage";
import type { TextContent } from "./TextContent";
import type { VideoCallContent } from "./VideoCallContent";
import type { VideoContent } from "./VideoContent";

export type MessageContent = { "Text": TextContent } | { "Image": ImageContent } | { "Video": VideoContent } | { "Audio": AudioContent } | { "File": FileContent } | { "Poll": PollContent } | { "Crypto": CryptoContent } | { "Deleted": DeletedBy } | { "Giphy": GiphyContent } | { "GovernanceProposal": ProposalContent } | { "Prize": PrizeContent } | { "PrizeWinner": PrizeWinnerContent } | { "MessageReminderCreated": MessageReminderCreatedContent } | { "MessageReminder": MessageReminderContent } | { "ReportedMessage": ReportedMessage } | { "P2PSwap": P2PSwapContent } | { "VideoCall": VideoCallContent } | { "Custom": CustomContent };
