// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Principal } from "./Principal";
import type { Proposal } from "./Proposal";

export type ProposalContent = { governance_canister_id: Principal, proposal: Proposal, my_vote?: boolean, };
