// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Principal } from "./Principal";

export type SnsNeuronGate = { governance_canister_id: Principal, min_stake_e8s?: bigint, min_dissolve_delay?: bigint, };
