// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPublicProfilePublicProfile = { username: string, display_name?: string | undefined, avatar_id?: bigint | undefined, bio: string, 
/**
 * @default false
 */
is_premium: boolean, 
/**
 * @default false
 */
phone_is_verified: boolean, created: bigint, };
