// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndexCurrentUserSuccessResult } from "./UserIndexCurrentUserSuccessResult";

export type UserIndexCurrentUserResponse = { "Success": UserIndexCurrentUserSuccessResult } | "UserNotFound";
