// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserUndeleteMessagesSuccessResult } from "./UserUndeleteMessagesSuccessResult";

export type UserUndeleteMessagesResponse = { "Success": UserUndeleteMessagesSuccessResult } | "ChatNotFound" | "UserSuspended";
