// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountICRC1 } from "../../shared/AccountICRC1";
import type { PinNumberWrapper } from "../../shared/PinNumberWrapper";
import type { TSPrincipal } from "../../shared/TSPrincipal";

export type UserApproveTransferArgs = { spender: AccountICRC1, ledger_canister_id: TSPrincipal, amount: bigint, expires_in?: bigint, pin?: PinNumberWrapper, };
