// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PushEventResult } from "../../shared/PushEventResult";

export type GroupPinMessageResponse = { "Success": PushEventResult } | "NoChange" | "MessageIndexOutOfRange" | "NotAuthorized" | "CallerNotInGroup" | "MessageNotFound" | "UserSuspended" | "UserLapsed" | "ChatFrozen";
