// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupUnblockUserResponse = "Success" | "CallerNotInGroup" | "CannotUnblockSelf" | "GroupNotPublic" | "NotAuthorized" | "UserSuspended" | "UserLapsed" | "ChatFrozen";
