// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";
import type { UserId } from "../../shared/UserId";

export type UserIndexUsersChitArgs = { 
/**
 * @default []
 */
users: Array<UserId>, year: TSNumberWithDefault, month: TSNumberWithDefault, };
