// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "../../shared/UserId";

export type UserIndexUsersChitArgs = { 
/**
 * @default []
 */
users: Array<UserId>, 
/**
 * @default 0
 */
year: number, 
/**
 * @default 0
 */
month: number, };
