import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { invoke } from "@tauri-apps/api/core";
import { inferenceRuntimeAvailable } from "tauri-plugin-oc-api";
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@tauri-apps/api/core", () => ({ invoke: vi.fn() }));

beforeEach(() => {
    vi.mocked(invoke).mockReset();
});

describe("native inference build capability bridge", () => {
    it.each([false, true])(
        "returns the installed binary's %s capability without inferring from platform",
        async (available) => {
            vi.mocked(invoke).mockResolvedValue(available);
            await expect(inferenceRuntimeAvailable()).resolves.toBe(available);
            expect(invoke).toHaveBeenCalledExactlyOnceWith("plugin:oc|inference_runtime_available");
        },
    );

    it("leaves an old binary's missing-command rejection observable to the facade", async () => {
        const error = new Error("command not found");
        vi.mocked(invoke).mockRejectedValue(error);
        await expect(inferenceRuntimeAvailable()).rejects.toBe(error);
    });

    it("registers the side-effect-free probe in every build and grants only its named permission", () => {
        const plugin = resolve(import.meta.dirname, "../../../tauri-plugin-oc");
        const read = (file: string) => readFileSync(resolve(plugin, file), "utf8");
        expect(read("src/commands.rs")).toMatch(
            /#\[command\]\s*pub\(crate\) fn inference_runtime_available\(\) -> bool \{\s*cfg!\(feature = "inference"\)\s*\}/,
        );
        expect(read("src/lib.rs")).toContain("commands::inference_runtime_available,");
        expect(read("build.rs")).toContain('"inference_runtime_available",');
        expect(read("permissions/default.toml")).toContain('"allow-inference-runtime-available",');
        const permission = read(
            "permissions/autogenerated/commands/inference_runtime_available.toml",
        );
        expect(permission).toContain('commands.allow = ["inference_runtime_available"]');
        expect(permission).toContain('commands.deny = ["inference_runtime_available"]');
    });
});
