import type { IDL } from "@dfinity/candid";
import {
    _SERVICE,
    CurrentUserResponse,
    CurrentUserArgs,
    CheckUsernameArgs,
    SetUsernameArgs,
    CheckUsernameResponse,
    SetUsernameResponse,
    UsersArgs,
    UsersResponse,
    UserSummary,
    PartialUserSummary,
    SearchArgs,
    SearchResponse,
    RegisterUserResponse,
    SuspendUserResponse,
    UnsuspendUserResponse,
    SuspensionDetails,
    SuspensionAction,
    DiamondMembershipDetails,
    DiamondMembershipPlanDuration,
    PayForDiamondMembershipResponse,
} from "./types";
export {
    _SERVICE as UserIndexService,
    CurrentUserResponse as ApiCurrentUserResponse,
    CurrentUserArgs as ApiCurrentUserArgs,
    SetUsernameArgs as ApiSetUsernameArgs,
    CheckUsernameResponse as ApiCheckUsernameResponse,
    SetUsernameResponse as ApiSetUsernameResponse,
    UsersArgs as ApiUsersArgs,
    UsersResponse as ApiUsersResponse,
    UserSummary as ApiUserSummary,
    PartialUserSummary as ApiPartialUserSummary,
    SearchArgs as ApiSearchArgs,
    SearchResponse as ApiSearchResponse,
    RegisterUserResponse as ApiRegisterUserResponse,
    SuspendUserResponse as ApiSuspendUserResponse,
    UnsuspendUserResponse as ApiUnsuspendUserResponse,
    SuspensionDetails as ApiSuspensionDetails,
    SuspensionAction as ApiSuspensionAction,
    DiamondMembershipDetails as ApiDiamondMembershipDetails,
    DiamondMembershipPlanDuration as ApiDiamondMembershipPlanDuration,
    PayForDiamondMembershipResponse as ApiPayForDiamondMembershipResponse,
};

export const idlFactory: IDL.InterfaceFactory;
