// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupReplyContext } from "../../shared/GroupReplyContext";
import type { MessageContentInitial } from "../../shared/MessageContentInitial";
import type { MessageId } from "../../shared/MessageId";
import type { MessageIndex } from "../../shared/MessageIndex";
import type { User } from "../../shared/User";
import type { Version } from "../../shared/Version";

export type CommunitySendMessageArgs = { channel_id: bigint, thread_root_message_index?: MessageIndex | undefined, message_id: MessageId, content: MessageContentInitial, sender_name: string, sender_display_name?: string | undefined, replies_to?: GroupReplyContext | undefined, 
/**
 * @default []
 */
mentioned: Array<User>, 
/**
 * @default false
 */
forwarding: boolean, 
/**
 * @default false
 */
block_level_markdown: boolean, community_rules_accepted?: Version | undefined, channel_rules_accepted?: Version | undefined, message_filter_failed?: bigint | undefined, 
/**
 * @default false
 */
new_achievement: boolean, };
