// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunitySendMessageSuccessResult } from "./CommunitySendMessageSuccessResult";
import type { InvalidPollReason } from "../../shared/InvalidPollReason";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type CommunitySendMessageResponse = { "Success": CommunitySendMessageSuccessResult } | "ChannelNotFound" | "ThreadMessageNotFound" | "MessageEmpty" | { "TextTooLong": TSNumberWithDefault } | { "InvalidPoll": InvalidPollReason } | "NotAuthorized" | "UserNotInCommunity" | "UserNotInChannel" | "UserSuspended" | { "InvalidRequest": string } | "CommunityFrozen" | "RulesNotAccepted" | "CommunityRulesNotAccepted" | "UserLapsed";
