pub mod c2c_create_group;
pub mod c2c_delete_group;
pub mod c2c_make_private;
pub mod c2c_mark_active;
pub mod c2c_notify_low_balance;
pub mod c2c_update_group;
pub mod freeze_group;
pub mod set_max_concurrent_canister_upgrades;
pub mod upgrade_group_canister_wasm;
