// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";

export type CommunityImportGroupSuccessResult = { channel_id: bigint, total_bytes: TSBigIntWithDefault, };
