// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityImportGroupSuccessResult } from "./CommunityImportGroupSuccessResult";

export type CommunityImportGroupResponse = { "Success": CommunityImportGroupSuccessResult } | "UserNotInCommunity" | "UserNotCommunityOwner" | "UserNotInGroup" | "UserNotGroupOwner" | "UserSuspended" | "GroupNotFound" | "GroupAlreadyBeingImported" | "GroupImportingToAnotherCommunity" | "GroupFrozen" | { "InternalError": string } | "UserLapsed";
