// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "../../shared/MessageIndex";
import type { VoteOperation } from "../../shared/VoteOperation";

export type CommunityRegisterPollVoteArgs = { channel_id: bigint, thread_root_message_index?: MessageIndex | undefined, 
/**
 * @default 0
 */
message_index: MessageIndex, 
/**
 * @default 0
 */
poll_option: number, operation: VoteOperation, 
/**
 * @default false
 */
new_achievement: boolean, };
