// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessTokenBotCommand } from "./AccessTokenBotCommand";
import type { VideoCallAccessTokenArgs } from "./VideoCallAccessTokenArgs";

export type AccessTokenType = { "StartVideoCallV2": VideoCallAccessTokenArgs } | "JoinVideoCall" | "MarkVideoCallAsEnded" | { "BotCommand": AccessTokenBotCommand };
