// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlobReference } from "./BlobReference";

export type AudioContent = { caption?: string | undefined, mime_type: string, blob_reference?: BlobReference | undefined, };
