// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotPermissions } from "./BotPermissions";

export type AutonomousConfig = { permissions: BotPermissions, };
