// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

export type AvatarChanged = { new_avatar?: bigint, previous_avatar?: bigint, changed_by: UserId, };
