// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSPrincipal } from "./TSPrincipal";

export type BlobReference = { canister_id: TSPrincipal, blob_id: bigint, };
