// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalTS } from "./PrincipalTS";

export type BlobReference = { canister_id: PrincipalTS, blob_id: bigint, };
