// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessTokenScope } from "./AccessTokenScope";
import type { TSBytes } from "./TSBytes";
import type { UserId } from "./UserId";

export type BotApiKeyToken = { gateway: TSBytes, bot_id: UserId, scope: AccessTokenScope, secret: string, };
