// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotActionChatDetails } from "./BotActionChatDetails";
import type { BotActionCommunityDetails } from "./BotActionCommunityDetails";

export type BotActionScope = { "Chat": BotActionChatDetails } | { "Community": BotActionCommunityDetails };
