// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotCommandParamType } from "./BotCommandParamType";

export type BotCommandParam = { name: string, description?: string, placeholder?: string, required: boolean, param_type: BotCommandParamType, };
