// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

export type BotCommandArgValue = { "String": string } | { "Integer": bigint } | { "Decimal": number } | { "Boolean": boolean } | { "User": UserId } | { "DateTime": bigint };
