// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotCommandParam } from "./BotCommandParam";
import type { BotPermissions } from "./BotPermissions";
import type { GroupRole } from "./GroupRole";

export type BotCommandDefinition = { name: string, description?: string, placeholder?: string, params: Array<BotCommandParam>, permissions: BotPermissions, default_role?: GroupRole, };
