// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "./MessageId";
import type { MessageIndex } from "./MessageIndex";
import type { UserId } from "./UserId";

export type BotCommandArgs = { user_id: UserId, bot: UserId, thread_root_message_index?: MessageIndex | undefined, message_id: MessageId, };
