// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutonomousConfig } from "./AutonomousConfig";
import type { BotCommandDefinition } from "./BotCommandDefinition";

export type BotDefinition = { description: string, commands: Array<BotCommandDefinition>, autonomous_config?: AutonomousConfig, };
