// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioContent } from "./AudioContent";
import type { CustomContent } from "./CustomContent";
import type { FileContent } from "./FileContent";
import type { GiphyContent } from "./GiphyContent";
import type { ImageContent } from "./ImageContent";
import type { PollContent } from "./PollContent";
import type { TextContent } from "./TextContent";
import type { VideoContent } from "./VideoContent";

export type BotMessageContent = { "Text": TextContent } | { "Image": ImageContent } | { "Video": VideoContent } | { "Audio": AudioContent } | { "File": FileContent } | { "Poll": PollContent } | { "Giphy": GiphyContent } | { "Custom": CustomContent };
