// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatPermission } from "./ChatPermission";
import type { CommunityPermission } from "./CommunityPermission";
import type { MessagePermission } from "./MessagePermission";

export type BotPermissions = { community: Array<CommunityPermission>, chat: Array<ChatPermission>, message: Array<MessagePermission>, };
