// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuildVersion = { 
/**
 * @default 0
 */
major: number, 
/**
 * @default 0
 */
minor: number, 
/**
 * @default 0
 */
patch: number, };
