// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { CommunityId } from "./CommunityId";
import type { CryptoTransferDetails } from "./CryptoTransferDetails";
import type { EventIndex } from "./EventIndex";
import type { MessageIndex } from "./MessageIndex";
import type { UserId } from "./UserId";

export type ChannelMessageNotification = { community_id: CommunityId, channel_id: ChannelId, thread_root_message_index?: MessageIndex, message_index: MessageIndex, event_index: EventIndex, community_name: string, channel_name: string, sender: UserId, sender_name: string, sender_display_name?: string, message_type: string, message_text?: string, image_url?: string, community_avatar_id?: bigint, channel_avatar_id?: bigint, crypto_transfer?: CryptoTransferDetails, };
