// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChitEarnedReason } from "./ChitEarnedReason";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type ChitEarned = { amount: TSNumberWithDefault, timestamp: TSBigIntWithDefault, reason: ChitEarnedReason, };
