// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityRole } from "./CommunityRole";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSBoolWithDefault } from "./TSBoolWithDefault";

export type CommunityMembership = { joined: TSBigIntWithDefault, role: CommunityRole, rules_accepted: TSBoolWithDefault, display_name?: string | undefined, lapsed: TSBoolWithDefault, };
