// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletedCryptoTransactionICRC1 } from "./CompletedCryptoTransactionICRC1";
import type { CompletedCryptoTransactionICRC2 } from "./CompletedCryptoTransactionICRC2";
import type { CompletedCryptoTransactionNNS } from "./CompletedCryptoTransactionNNS";

export type CompletedCryptoTransaction = { "NNS": CompletedCryptoTransactionNNS } | { "ICRC1": CompletedCryptoTransactionICRC1 } | { "ICRC2": CompletedCryptoTransactionICRC2 };
