// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoAccountNNS } from "./CryptoAccountNNS";
import type { Cryptocurrency } from "./Cryptocurrency";
import type { PrincipalTS } from "./PrincipalTS";
import type { Tokens } from "./Tokens";

export type CompletedCryptoTransactionNNS = { ledger: PrincipalTS, token: Cryptocurrency, amount: Tokens, fee: Tokens, from: CryptoAccountNNS, to: CryptoAccountNNS, memo: bigint, created: bigint, transaction_hash: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], block_index: bigint, };
