// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoAccountICRC1 } from "./CryptoAccountICRC1";
import type { Cryptocurrency } from "./Cryptocurrency";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSBytes } from "./TSBytes";

export type CompletedCryptoTransactionICRC1 = { ledger: TSBytes, token: Cryptocurrency, amount: TSBigIntWithDefault, from: CryptoAccountICRC1, to: CryptoAccountICRC1, fee: TSBigIntWithDefault, memo?: TSBytes | undefined, created: TSBigIntWithDefault, block_index: TSBigIntWithDefault, };
