// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletedCryptoTransaction } from "./CompletedCryptoTransaction";
import type { FailedCryptoTransaction } from "./FailedCryptoTransaction";
import type { PendingCryptoTransaction } from "./PendingCryptoTransaction";

export type CryptoTransaction = { "Pending": PendingCryptoTransaction } | { "Completed": CompletedCryptoTransaction } | { "Failed": FailedCryptoTransaction };
