// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotCommandOptionChoiceF64 } from "./BotCommandOptionChoiceF64";

export type DecimalParam = { min_value: number, max_value: number, choices: Array<BotCommandOptionChoiceF64>, };
