// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityId } from "./CommunityId";
import type { UserId } from "./UserId";

export type DeletedCommunityInfo = { id: CommunityId, timestamp: bigint, deleted_by: UserId, name: string, 
/**
 * @default false
 */
public: boolean, };
