// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBytes } from "./TSBytes";

export type Delegation = { pubkey: TSBytes, expiration: bigint, };
