// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "./ChatId";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSBoolWithDefault } from "./TSBoolWithDefault";
import type { UserId } from "./UserId";

export type DeletedGroupInfo = { id: ChatId, timestamp: TSBigIntWithDefault, deleted_by: UserId, group_name: string, name: string, public: TSBoolWithDefault, };
