// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiamondMembershipSubscription } from "./DiamondMembershipSubscription";
import type { TSBoolWithDefault } from "./TSBoolWithDefault";

export type DiamondMembershipDetails = { expires_at: bigint, pay_in_chat: TSBoolWithDefault, subscription: DiamondMembershipSubscription, };
