// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiamondMembershipFeesByDuration } from "./DiamondMembershipFeesByDuration";

export type DiamondMembershipFees = { chat_fees: DiamondMembershipFeesByDuration, icp_fees: DiamondMembershipFeesByDuration, };
