// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventIndex } from "./EventIndex";
import type { MessageIndex } from "./MessageIndex";
import type { UserId } from "./UserId";

export type DirectMessageTipped = { ti: UserId, tr?: MessageIndex, m: MessageIndex, e: EventIndex, u: string, d?: string, t: string, a?: bigint, };
