// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventIndex } from "./EventIndex";
import type { MessageIndex } from "./MessageIndex";
import type { Reaction } from "./Reaction";
import type { UserId } from "./UserId";

export type DirectReactionAddedNotification = { them: UserId, thread_root_message_index?: MessageIndex, message_index: MessageIndex, message_event_index: EventIndex, username: string, display_name?: string, reaction: Reaction, user_avatar_id?: bigint, };
