// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type EventWrapperMessage = { index: TSNumberWithDefault, timestamp: TSBigIntWithDefault, correlation_id: TSBigIntWithDefault, expires_at?: bigint | undefined, event: Message, };
