// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventIndex } from "./EventIndex";
import type { GroupFrozen } from "./GroupFrozen";

export type EventWrapperGroupFrozen = { 
/**
 * @default 0
 */
index: EventIndex, timestamp: bigint, correlation_id: bigint, expires_at?: bigint | undefined, event: GroupFrozen, };
