// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupFrozen } from "./GroupFrozen";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type EventWrapperGroupFrozen = { index: TSNumberWithDefault, timestamp: TSBigIntWithDefault, correlation_id: TSBigIntWithDefault, expires_at?: bigint | undefined, event: GroupFrozen, };
