// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailedCryptoTransactionICRC1 } from "./FailedCryptoTransactionICRC1";
import type { FailedCryptoTransactionICRC2 } from "./FailedCryptoTransactionICRC2";
import type { FailedCryptoTransactionNNS } from "./FailedCryptoTransactionNNS";

export type FailedCryptoTransaction = { "NNS": FailedCryptoTransactionNNS } | { "ICRC1": FailedCryptoTransactionICRC1 } | { "ICRC2": FailedCryptoTransactionICRC2 };
