// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldTooShortResult = { 
/**
 * @default 0
 */
length_provided: number, 
/**
 * @default 0
 */
min_length: number, };
