// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type FieldTooShortResult = { length_provided: TSNumberWithDefault, min_length: TSNumberWithDefault, };
