// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlobReference } from "./BlobReference";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type FileContent = { name: string, caption?: string | undefined, mime_type: string, file_size: TSNumberWithDefault, blob_reference?: BlobReference | undefined, };
