// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { UserId } from "./UserId";

export type FrozenGroupInfo = { timestamp: TSBigIntWithDefault, frozen_by: UserId, reason?: string | undefined, };
