// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GiphyImageVariant = { 
/**
 * @default 0
 */
width: number, 
/**
 * @default 0
 */
height: number, url: string, mime_type: string, };
