// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "./ChatId";
import type { EventIndex } from "./EventIndex";
import type { MessageIndex } from "./MessageIndex";
import type { Reaction } from "./Reaction";
import type { UserId } from "./UserId";

export type GroupReactionAddedNotification = { c: ChatId, tr?: MessageIndex, m: MessageIndex, e: EventIndex, g: string, a: UserId, n: string, d?: string, r: Reaction, av?: bigint, };
