// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "./ChatId";
import type { CryptoTransferDetails } from "./CryptoTransferDetails";
import type { EventIndex } from "./EventIndex";
import type { MessageIndex } from "./MessageIndex";
import type { UserId } from "./UserId";

export type GroupMessageNotification = { chat_id: ChatId, thread_root_message_index?: MessageIndex, message_index: MessageIndex, event_index: EventIndex, group_name: string, sender: UserId, sender_name: string, sender_display_name?: string, message_type: string, message_text?: string, image_url?: string, group_avatar_id?: bigint, crypto_transfer?: CryptoTransferDetails, };
