// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupRole } from "./GroupRole";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSBoolWithDefault } from "./TSBoolWithDefault";
import type { UserId } from "./UserId";

export type GroupMember = { user_id: UserId, date_added: TSBigIntWithDefault, role: GroupRole, lapsed: TSBoolWithDefault, };
