// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

export type GroupCreated = { name: string, description: string, created_by: UserId, };
