// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildVersion } from "./BuildVersion";
import type { ChatId } from "./ChatId";
import type { ChatMetrics } from "./ChatMetrics";
import type { EventIndex } from "./EventIndex";
import type { EventWrapperMessage } from "./EventWrapperMessage";
import type { GroupCanisterThreadDetails } from "./GroupCanisterThreadDetails";
import type { GroupMembershipUpdates } from "./GroupMembershipUpdates";
import type { GroupPermissions } from "./GroupPermissions";
import type { GroupRole } from "./GroupRole";
import type { HydratedMention } from "./HydratedMention";
import type { MessageIndex } from "./MessageIndex";
import type { OptionUpdateAccessGate } from "./OptionUpdateAccessGate";
import type { OptionUpdateAccessGateConfig } from "./OptionUpdateAccessGateConfig";
import type { OptionUpdateFrozenGroupInfo } from "./OptionUpdateFrozenGroupInfo";
import type { OptionUpdateGroupSubtype } from "./OptionUpdateGroupSubtype";
import type { OptionUpdateU128 } from "./OptionUpdateU128";
import type { OptionUpdateU64 } from "./OptionUpdateU64";
import type { OptionUpdateVideoCall } from "./OptionUpdateVideoCall";

export type GroupCanisterGroupChatSummaryUpdates = { chat_id: ChatId, last_updated: bigint, name?: string, description?: string, subtype: OptionUpdateGroupSubtype, avatar_id: OptionUpdateU128, latest_message?: EventWrapperMessage, latest_event_index?: EventIndex, latest_message_index?: MessageIndex, participant_count?: number, role?: GroupRole, mentions: Array<HydratedMention>, wasm_version?: BuildVersion, permissions_v2?: GroupPermissions, updated_events: Array<[MessageIndex | null, EventIndex, bigint]>, metrics?: ChatMetrics, my_metrics?: ChatMetrics, is_public?: boolean, messages_visible_to_non_members?: boolean, latest_threads: Array<GroupCanisterThreadDetails>, unfollowed_threads: Array<MessageIndex>, notifications_muted?: boolean, frozen: OptionUpdateFrozenGroupInfo, date_last_pinned?: bigint, events_ttl: OptionUpdateU64, events_ttl_last_updated?: bigint, gate: OptionUpdateAccessGate, gate_config: OptionUpdateAccessGateConfig, rules_accepted?: boolean, membership?: GroupMembershipUpdates, video_call_in_progress: OptionUpdateVideoCall, any_updates_missed: boolean, verified?: boolean, };
