// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMetrics } from "./ChatMetrics";
import type { GroupCanisterThreadDetails } from "./GroupCanisterThreadDetails";
import type { GroupRole } from "./GroupRole";
import type { HydratedMention } from "./HydratedMention";
import type { MessageIndex } from "./MessageIndex";

export type GroupMembershipUpdates = { role?: GroupRole | undefined, 
/**
 * @default []
 */
mentions: Array<HydratedMention>, notifications_muted?: boolean | undefined, my_metrics?: ChatMetrics | undefined, 
/**
 * @default []
 */
latest_threads: Array<GroupCanisterThreadDetails>, 
/**
 * @default []
 */
unfollowed_threads: Array<MessageIndex>, rules_accepted?: boolean | undefined, lapsed?: boolean | undefined, };
