// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessGate } from "./AccessGate";
import type { AccessGateConfig } from "./AccessGateConfig";
import type { UserId } from "./UserId";

export type GroupGateUpdated = { updated_by: UserId, new_gate?: AccessGate, new_gate_config?: AccessGateConfig, };
