// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessGate } from "./AccessGate";
import type { ChatId } from "./ChatId";
import type { GroupSubtype } from "./GroupSubtype";

export type GroupMatch = { id: ChatId, name: string, description: string, avatar_id?: bigint | undefined, 
/**
 * @default 0
 */
member_count: number, gate?: AccessGate | undefined, subtype?: GroupSubtype | undefined, };
