// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InvalidPollReason = { "TooFewOptions": number } | { "TooManyOptions": number } | { "OptionTooLong": number } | "DuplicateOptions" | "EndDateInThePast" | "PollsNotValidForDirectChats";
