// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBoolWithDefault } from "./TSBoolWithDefault";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";
import type { UserId } from "./UserId";

export type MessageUnpinned = { message_index: TSNumberWithDefault, unpinned_by: UserId, due_to_message_deleted: TSBoolWithDefault, };
