// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSNumberWithDefault } from "./TSNumberWithDefault";
import type { UserId } from "./UserId";

export type MessageReport = { reported_by: UserId, timestamp: bigint, reason_code: TSNumberWithDefault, notes?: string | undefined, };
