// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "./MessageIndex";
import type { UserId } from "./UserId";

export type MessageUnpinned = { 
/**
 * @default 0
 */
message_index: MessageIndex, unpinned_by: UserId, 
/**
 * @default false
 */
due_to_message_deleted: boolean, };
