// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageContent } from "./MessageContent";
import type { MessageId } from "./MessageId";
import type { Reaction } from "./Reaction";
import type { ReplyContext } from "./ReplyContext";
import type { TSBoolWithDefault } from "./TSBoolWithDefault";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";
import type { ThreadSummary } from "./ThreadSummary";
import type { Tips } from "./Tips";
import type { UserId } from "./UserId";

export type Message = { message_index: TSNumberWithDefault, message_id: MessageId, sender: UserId, content: MessageContent, replies_to?: ReplyContext | undefined, 
/**
 * @default []
 */
reactions: Array<[Reaction, Array<UserId>]>, tips: Tips, thread_summary?: ThreadSummary | undefined, edited: TSBoolWithDefault, forwarded: TSBoolWithDefault, block_level_markdown: TSBoolWithDefault, };
