// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventWrapperMessage } from "./EventWrapperMessage";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type MessagesResponse = { 
/**
 * @default []
 */
messages: Array<EventWrapperMessage>, latest_event_index: TSNumberWithDefault, chat_last_updated: TSBigIntWithDefault, };
