// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "./MessageIndex";

export type MessageMatch = { message_index: MessageIndex, score: number, };
