// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventIndex } from "./EventIndex";
import type { EventWrapperMessage } from "./EventWrapperMessage";

export type MessagesResponse = { messages: Array<EventWrapperMessage>, latest_event_index: EventIndex, chat_last_updated: bigint, };
