// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBoolWithDefault } from "./TSBoolWithDefault";

export type MessageReminderCreatedContent = { reminder_id: bigint, remind_at: bigint, notes?: string | undefined, hidden: TSBoolWithDefault, };
