// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageReminderContent = { reminder_id: bigint, notes?: string | undefined, };
