// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposalDecisionStatus } from "./ProposalDecisionStatus";
import type { ProposalRewardStatus } from "./ProposalRewardStatus";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";
import type { Tally } from "./Tally";

export type NnsProposal = { id: bigint, topic: TSNumberWithDefault, proposer: bigint, created: TSBigIntWithDefault, title: string, summary: string, url: string, status: ProposalDecisionStatus, reward_status: ProposalRewardStatus, tally: Tally, deadline: TSBigIntWithDefault, payload_text_rendering?: string | undefined, last_updated: TSBigIntWithDefault, };
