// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlashCommandOptionChoiceU16 } from "./SlashCommandOptionChoiceU16";

export type NumberParam = { min_length: number, max_length: number, choices: SlashCommandOptionChoiceU16, };
