// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomPermission } from "./CustomPermission";
import type { GroupPermissionRole } from "./GroupPermissionRole";
import type { OptionUpdateGroupPermissionRole } from "./OptionUpdateGroupPermissionRole";

export type OptionalMessagePermissions = { default?: GroupPermissionRole | undefined, 
/**
 * @default NoChange
 */
text: OptionUpdateGroupPermissionRole, 
/**
 * @default NoChange
 */
image: OptionUpdateGroupPermissionRole, 
/**
 * @default NoChange
 */
video: OptionUpdateGroupPermissionRole, 
/**
 * @default NoChange
 */
audio: OptionUpdateGroupPermissionRole, 
/**
 * @default NoChange
 */
file: OptionUpdateGroupPermissionRole, 
/**
 * @default NoChange
 */
poll: OptionUpdateGroupPermissionRole, 
/**
 * @default NoChange
 */
crypto: OptionUpdateGroupPermissionRole, 
/**
 * @default NoChange
 */
giphy: OptionUpdateGroupPermissionRole, 
/**
 * @default NoChange
 */
prize: OptionUpdateGroupPermissionRole, 
/**
 * @default NoChange
 */
p2p_swap: OptionUpdateGroupPermissionRole, 
/**
 * @default NoChange
 */
video_call: OptionUpdateGroupPermissionRole, 
/**
 * @default []
 */
custom_updated: Array<CustomPermission>, 
/**
 * @default []
 */
custom_deleted: Array<string>, };
