// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinNumberSettings } from "./PinNumberSettings";

/**
 * @default NoChange
 */
export type OptionUpdatePinNumberSettings = "NoChange" | "SetToNone" | { "SetToSome": PinNumberSettings };
