// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupPermissionRole } from "./GroupPermissionRole";

export type OptionUpdateGroupPermissionRole = "NoChange" | "SetToNone" | { "SetToSome": GroupPermissionRole };
