// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityPermissionRole } from "./CommunityPermissionRole";

export type OptionalCommunityPermissions = { change_roles?: CommunityPermissionRole, update_details?: CommunityPermissionRole, invite_users?: CommunityPermissionRole, remove_members?: CommunityPermissionRole, create_public_channel?: CommunityPermissionRole, create_private_channel?: CommunityPermissionRole, manage_user_groups?: CommunityPermissionRole, };
