// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityPermissionRole } from "./CommunityPermissionRole";

export type OptionalCommunityPermissions = { change_roles?: CommunityPermissionRole | undefined, update_details?: CommunityPermissionRole | undefined, invite_users?: CommunityPermissionRole | undefined, remove_members?: CommunityPermissionRole | undefined, create_public_channel?: CommunityPermissionRole | undefined, create_private_channel?: CommunityPermissionRole | undefined, manage_user_groups?: CommunityPermissionRole | undefined, };
