// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessGateConfig } from "./AccessGateConfig";

/**
 * @default NoChange
 */
export type OptionUpdateAccessGateConfig = "NoChange" | "SetToNone" | { "SetToSome": AccessGateConfig };
