// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @default NoChange
 */
export type OptionUpdateString = "NoChange" | "SetToNone" | { "SetToSome": string };
