// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrozenGroupInfo } from "./FrozenGroupInfo";

/**
 * @default NoChange
 */
export type OptionUpdateFrozenGroupInfo = "NoChange" | "SetToNone" | { "SetToSome": FrozenGroupInfo };
