// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenInfo } from "./TokenInfo";

export type P2PSwapContentInitial = { token0: TokenInfo, token0_amount: bigint, token1: TokenInfo, token1_amount: bigint, expires_in: bigint, caption?: string, };
