// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TokenInfo } from "./TokenInfo";

export type P2PSwapContentInitial = { token0: TokenInfo, token0_amount: TSBigIntWithDefault, token1: TokenInfo, token1_amount: TSBigIntWithDefault, expires_in: TSBigIntWithDefault, caption?: string | undefined, };
