// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSBytes } from "./TSBytes";

export type PaymentGate = { ledger_canister_id: TSBytes, amount: TSBigIntWithDefault, fee: TSBigIntWithDefault, };
