// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountICRC1 } from "./AccountICRC1";
import type { Cryptocurrency } from "./Cryptocurrency";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSBytes } from "./TSBytes";

export type PendingCryptoTransactionICRC2 = { ledger: TSBytes, token: Cryptocurrency, amount: TSBigIntWithDefault, from: AccountICRC1, to: AccountICRC1, fee: TSBigIntWithDefault, memo?: TSBytes | undefined, created: TSBigIntWithDefault, };
