// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountICRC1 } from "./AccountICRC1";
import type { Cryptocurrency } from "./Cryptocurrency";
import type { PrincipalTS } from "./PrincipalTS";

export type PendingCryptoTransactionICRC2 = { ledger: PrincipalTS, token: Cryptocurrency, amount: bigint, from: AccountICRC1, to: AccountICRC1, fee: bigint, memo?: Array<number>, created: bigint, };
