// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PollConfig } from "./PollConfig";
import type { PollVotes } from "./PollVotes";
import type { TSBoolWithDefault } from "./TSBoolWithDefault";

export type PollContent = { config: PollConfig, votes: PollVotes, ended: TSBoolWithDefault, };
