// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TotalVotes } from "./TotalVotes";

export type PollVotes = { total: TotalVotes, 
/**
 * @default []
 */
user: Array<number>, };
