// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBoolWithDefault } from "./TSBoolWithDefault";

export type PollConfig = { text?: string | undefined, 
/**
 * @default []
 */
options: Array<string>, end_date?: bigint | undefined, anonymous: TSBoolWithDefault, show_votes_before_end_date: TSBoolWithDefault, allow_multiple_votes_per_user: TSBoolWithDefault, allow_user_to_change_vote: TSBoolWithDefault, };
