// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletedCryptoTransaction } from "./CompletedCryptoTransaction";
import type { MessageIndex } from "./MessageIndex";
import type { UserId } from "./UserId";

export type PrizeWinnerContent = { winner: UserId, transaction: CompletedCryptoTransaction, 
/**
 * @default 0
 */
prize_message: MessageIndex, };
