// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cryptocurrency } from "./Cryptocurrency";
import type { TSBoolWithDefault } from "./TSBoolWithDefault";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";
import type { UserId } from "./UserId";

export type PrizeContent = { prizes_remaining: TSNumberWithDefault, prizes_pending: TSNumberWithDefault, 
/**
 * @default []
 */
winners: Array<UserId>, winner_count: TSNumberWithDefault, user_is_winner: TSBoolWithDefault, token: Cryptocurrency, end_date: bigint, caption?: string | undefined, diamond_only: TSBoolWithDefault, };
