// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalTS } from "./PrincipalTS";
import type { Proposal } from "./Proposal";

export type ProposalContent = { governance_canister_id: PrincipalTS, proposal: Proposal, my_vote?: boolean, };
