// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type PushEventResult = { index: TSNumberWithDefault, timestamp: TSBigIntWithDefault, expires_at?: bigint | undefined, };
