// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chat } from "./Chat";
import type { MessageIndex } from "./MessageIndex";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type ReplyContext = { chat_if_other?: [Chat, MessageIndex | null] | undefined, event_index: TSNumberWithDefault, };
