// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chat } from "./Chat";
import type { EventIndex } from "./EventIndex";
import type { MessageIndex } from "./MessageIndex";

export type ReplyContext = { chat_if_other?: [Chat, MessageIndex | null] | undefined, event_index: EventIndex, };
