// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageReport } from "./MessageReport";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type ReportedMessage = { 
/**
 * @default []
 */
reports: Array<MessageReport>, count: TSNumberWithDefault, };
