// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupRole } from "./GroupRole";
import type { UserId } from "./UserId";

export type RoleChanged = { 
/**
 * @default []
 */
user_ids: Array<UserId>, changed_by: UserId, old_role: GroupRole, new_role: GroupRole, };
