// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupMember } from "./GroupMember";
import type { MessageIndex } from "./MessageIndex";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";
import type { UserId } from "./UserId";
import type { VersionedRules } from "./VersionedRules";

export type SelectedGroupUpdates = { timestamp: bigint, last_updated: bigint, latest_event_index: TSNumberWithDefault, 
/**
 * @default []
 */
members_added_or_updated: Array<GroupMember>, 
/**
 * @default []
 */
members_removed: Array<UserId>, 
/**
 * @default []
 */
blocked_users_added: Array<UserId>, 
/**
 * @default []
 */
blocked_users_removed: Array<UserId>, invited_users?: Array<UserId> | undefined, 
/**
 * @default []
 */
pinned_messages_added: Array<MessageIndex>, 
/**
 * @default []
 */
pinned_messages_removed: Array<MessageIndex>, chat_rules?: VersionedRules | undefined, };
