// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delegation } from "./Delegation";
import type { TSBytes } from "./TSBytes";

export type SignedDelegation = { delegation: Delegation, signature: TSBytes, };
