// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlashCommandParam } from "./SlashCommandParam";
import type { SlashCommandPermissions } from "./SlashCommandPermissions";

export type SlashCommandSchema = { name: string, description?: string | undefined, placeholder?: string | undefined, params: Array<SlashCommandParam>, permissions: SlashCommandPermissions, };
