// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chat } from "./Chat";
import type { VideoCallType } from "./VideoCallType";

export type StartVideoCallArgs = { call_type: VideoCallType, chat: Chat, };
