// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuspensionAction } from "./SuspensionAction";
import type { UserId } from "./UserId";

export type SuspensionDetails = { reason: string, action: SuspensionAction, suspended_by: UserId, };
