// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { UserId } from "./UserId";

export type SwapStatusErrorAccepted = { accepted_by: UserId, token1_txn_in: TSBigIntWithDefault, };
