// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

export type SwapStatusErrorCompleted = { accepted_by: UserId, token1_txn_in: bigint, token0_txn_out: bigint, token1_txn_out: bigint, };
