// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";

export type Tally = { yes: TSBigIntWithDefault, no: TSBigIntWithDefault, total: TSBigIntWithDefault, timestamp: TSBigIntWithDefault, };
