// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventWrapperMessage } from "./EventWrapperMessage";

export type ThreadPreview = { root_message: EventWrapperMessage, latest_replies: Array<EventWrapperMessage>, total_replies: number, };
