// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventWrapperMessage } from "./EventWrapperMessage";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type ThreadPreview = { root_message: EventWrapperMessage, 
/**
 * @default []
 */
latest_replies: Array<EventWrapperMessage>, total_replies: TSNumberWithDefault, };
