// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventIndex } from "./EventIndex";
import type { UserId } from "./UserId";

export type ThreadSummary = { 
/**
 * @default []
 */
participant_ids: Array<UserId>, 
/**
 * @default false
 */
followed_by_me: boolean, 
/**
 * @default 0
 */
reply_count: number, 
/**
 * @default 0
 */
latest_event_index: EventIndex, latest_event_timestamp: bigint, };
