// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalTS } from "./PrincipalTS";

export type TokenBalanceGate = { ledger_canister_id: PrincipalTS, min_balance: bigint, };
