// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSPrincipal } from "./TSPrincipal";

export type TokenBalanceGate = { ledger_canister_id: TSPrincipal, min_balance: bigint, };
