// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cryptocurrency } from "./Cryptocurrency";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";
import type { TSBytes } from "./TSBytes";
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type TokenInfo = { token: Cryptocurrency, ledger: TSBytes, decimals: TSNumberWithDefault, fee: TSBigIntWithDefault, };
