// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBytes } from "./TSBytes";

export type TokenBalanceGate = { ledger_canister_id: TSBytes, min_balance: bigint, };
