// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSummaryVolatile = { total_chit_earned: number, chit_balance: number, streak: number, max_streak: number, };
