// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotConfig } from "./BotConfig";
import type { DiamondMembershipStatus } from "./DiamondMembershipStatus";

export type UserSummaryStable = { username: string, display_name?: string | undefined, avatar_id?: bigint | undefined, 
/**
 * @default false
 */
is_bot: boolean, 
/**
 * @default false
 */
suspended: boolean, diamond_membership_status: DiamondMembershipStatus, 
/**
 * @default false
 */
is_unique_person: boolean, bot_config?: BotConfig | undefined, };
