// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

export type UsersInvited = { user_ids: Array<UserId>, invited_by: UserId, };
