// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

export type UsersBlocked = { 
/**
 * @default []
 */
user_ids: Array<UserId>, blocked_by: UserId, };
