// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiamondMembershipStatus } from "./DiamondMembershipStatus";

export type UserSummaryStable = { username: string, display_name?: string, avatar_id?: bigint, is_bot: boolean, suspended: boolean, diamond_membership_status: DiamondMembershipStatus, is_unique_person: boolean, };
