// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiamondMembershipStatus } from "./DiamondMembershipStatus";
import type { UserId } from "./UserId";

export type UserSummary = { user_id: UserId, username: string, display_name?: string | undefined, avatar_id?: bigint | undefined, 
/**
 * @default false
 */
is_bot: boolean, 
/**
 * @default false
 */
suspended: boolean, 
/**
 * @default false
 */
diamond_member: boolean, diamond_membership_status: DiamondMembershipStatus, 
/**
 * @default 0
 */
total_chit_earned: number, 
/**
 * @default 0
 */
chit_balance: number, 
/**
 * @default 0
 */
streak: number, 
/**
 * @default false
 */
is_unique_person: boolean, };
