// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiamondMembershipStatus } from "./DiamondMembershipStatus";
import type { UserId } from "./UserId";

export type UserSummary = { user_id: UserId, username: string, display_name?: string | undefined, avatar_id?: bigint | undefined, is_bot: boolean, suspended: boolean, diamond_member: boolean, diamond_membership_status: DiamondMembershipStatus, total_chit_earned: number, chit_balance: number, streak: number, is_unique_person: boolean, };
