// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

export type UserGroupDetails = { 
/**
 * @default 0
 */
user_group_id: number, name: string, 
/**
 * @default []
 */
members: Array<UserId>, };
