// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSNumberWithDefault } from "./TSNumberWithDefault";

export type VerifiedCredentialArgumentValue = { "String": string } | { "Int": TSNumberWithDefault };
