// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalTS } from "./PrincipalTS";

export type VerifiedCredentialGateArgs = { user_ii_principal: PrincipalTS, credential_jwt: string, credential_jwts: Array<string>, ii_origin: string, };
