// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalTS } from "./PrincipalTS";
import type { VerifiedCredentialArgumentValue } from "./VerifiedCredentialArgumentValue";

export type VerifiedCredentialGate = { issuer_canister_id: PrincipalTS, issuer_origin: string, credential_type: string, credential_name: string, credential_arguments: { [key: string]: VerifiedCredentialArgumentValue }, };
