// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallParticipant } from "./CallParticipant";

export type VideoCallParticipants = { participants: Array<CallParticipant>, hidden: Array<CallParticipant>, last_updated: bigint, };
