// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "./MessageIndex";
import type { VideoCallType } from "./VideoCallType";

export type VideoCall = { message_index: MessageIndex, call_type: VideoCallType, };
