// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallParticipant } from "./CallParticipant";
import type { TSBigIntWithDefault } from "./TSBigIntWithDefault";

export type VideoCallParticipants = { 
/**
 * @default []
 */
participants: Array<CallParticipant>, 
/**
 * @default []
 */
hidden: Array<CallParticipant>, last_updated: TSBigIntWithDefault, };
