// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "../../shared/MessageId";
import type { VideoCallPresence } from "../../shared/VideoCallPresence";

export type CommunitySetVideoCallPresenceArgs = { channel_id: bigint, message_id: MessageId, presence: VideoCallPresence, 
/**
 * @default false
 */
new_achievement: boolean, };
