// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "../../shared/ChannelId";
import type { MessageId } from "../../shared/MessageId";
import type { VideoCallPresence } from "../../shared/VideoCallPresence";

export type CommunitySetVideoCallPresenceArgs = { channel_id: ChannelId, message_id: MessageId, presence: VideoCallPresence, new_achievement: boolean, };
