// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageIndex } from "../../shared/MessageIndex";

export type CommunityRegisterProposalVoteV2Args = { channel_id: bigint, 
/**
 * @default 0
 */
message_index: MessageIndex, 
/**
 * @default false
 */
adopt: boolean, };
