// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBoolWithDefault } from "../../shared/TSBoolWithDefault";
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type CommunityRegisterProposalVoteV2Args = { channel_id: bigint, message_index: TSNumberWithDefault, adopt: TSBoolWithDefault, };
