// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "../../shared/ChannelId";
import type { MessageIndex } from "../../shared/MessageIndex";

export type CommunityRegisterProposalVoteV2Args = { channel_id: ChannelId, message_index: MessageIndex, adopt: boolean, };
