import type { ApiEventsResponse, ApiUpdatesResponse, ApiCreateGroupResponse, ApiDeleteGroupResponse, ApiSendMessageResponse, ApiBlockUserResponse, ApiUnblockUserResponse, ApiLeaveGroupResponse, ApiMarkReadResponse, ApiSetAvatarResponse, ApiAddReactionResponse, ApiRemoveReactionResponse, ApiDeleteMessageResponse, ApiJoinGroupResponse, ApiSearchDirectChatResponse, ApiSearchAllMessagesResponse, ApiMessageMatch, ApiEditMessageResponse, ApiInitialStateResponse, ApiRecommendedGroupsResponse, ApiSetBioResponse, ApiWithdrawCryptoResponse, ApiTransferCryptoWithinGroupResponse, ApiPublicProfileResponse, ApiPinChatResponse, ApiUnpinChatResponse, ApiMigrateUserPrincipalResponse, ApiGroupSubtype, ApiArchiveChatResponse } from "./candid/idl";
import type { UpdatesResponse, EventsResponse, CreateGroupResponse, DeleteGroupResponse, DirectChatEvent, SendMessageResponse, BlockUserResponse, UnblockUserResponse, LeaveGroupResponse, MarkReadResponse, SetAvatarResponse, AddRemoveReactionResponse, DeleteMessageResponse, JoinGroupResponse, EditMessageResponse, InitialStateResponse, GroupChatSummary, WithdrawCryptocurrencyResponse, GroupSubtype } from "../../domain/chat/chat";
import type { MessageMatch, SearchDirectChatResponse, SearchAllMessagesResponse } from "../../domain/search/search";
import type { ArchiveChatResponse, MigrateUserPrincipalResponse, PinChatResponse, PublicProfile, SetBioResponse, UnpinChatResponse } from "../../domain/user/user";
export declare function publicProfileResponse(candid: ApiPublicProfileResponse): PublicProfile;
export declare function setBioResponse(candid: ApiSetBioResponse): SetBioResponse;
export declare function recommendedGroupsResponse(candid: ApiRecommendedGroupsResponse): GroupChatSummary[];
export declare function searchAllMessagesResponse(candid: ApiSearchAllMessagesResponse): SearchAllMessagesResponse;
export declare function searchDirectChatResponse(candid: ApiSearchDirectChatResponse): SearchDirectChatResponse;
export declare function messageMatch(candid: ApiMessageMatch): MessageMatch;
export declare function deleteMessageResponse(candid: ApiDeleteMessageResponse): DeleteMessageResponse;
export declare function addRemoveReactionResponse(candid: ApiAddReactionResponse | ApiRemoveReactionResponse): AddRemoveReactionResponse;
export declare function setAvatarResponse(candid: ApiSetAvatarResponse): SetAvatarResponse;
export declare function markReadResponse(_candid: ApiMarkReadResponse): MarkReadResponse;
export declare function leaveGroupResponse(candid: ApiLeaveGroupResponse): LeaveGroupResponse;
export declare function joinGroupResponse(candid: ApiJoinGroupResponse): JoinGroupResponse;
export declare function blockResponse(_candid: ApiBlockUserResponse): BlockUserResponse;
export declare function unblockResponse(_candid: ApiUnblockUserResponse): UnblockUserResponse;
export declare function pinChatResponse(candid: ApiPinChatResponse): PinChatResponse;
export declare function unpinChatResponse(_candid: ApiUnpinChatResponse): UnpinChatResponse;
export declare function archiveChatResponse(candid: ApiArchiveChatResponse): ArchiveChatResponse;
export declare function editMessageResponse(candid: ApiEditMessageResponse): EditMessageResponse;
export declare function transferWithinGroupResponse(candid: ApiTransferCryptoWithinGroupResponse, sender: string, recipient: string): SendMessageResponse;
export declare function sendMessageResponse(candid: ApiSendMessageResponse, sender: string, recipient: string): SendMessageResponse;
export declare function createGroupResponse(candid: ApiCreateGroupResponse): CreateGroupResponse;
export declare function deleteGroupResponse(candid: ApiDeleteGroupResponse): DeleteGroupResponse;
export declare function getEventsResponse(candid: ApiEventsResponse, chatId: string, latestClientEventIndexPreRequest: number | undefined): EventsResponse<DirectChatEvent>;
export declare function initialStateResponse(candid: ApiInitialStateResponse): InitialStateResponse;
export declare function getUpdatesResponse(candid: ApiUpdatesResponse): UpdatesResponse;
export declare function apiGroupSubtype(subtype: ApiGroupSubtype): GroupSubtype;
export declare function withdrawCryptoResponse(candid: ApiWithdrawCryptoResponse): WithdrawCryptocurrencyResponse;
export declare function migrateUserPrincipal(candid: ApiMigrateUserPrincipalResponse): MigrateUserPrincipalResponse;
