import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { ownedSecurityRules } from "./security_owned_rules.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));
const policies = existsSync(
  resolve(root, "scripts/check_openchat_pr2_security.mjs"),
)
  ? ["pr1", "pr2"]
  : ["pr1"];
const notices = [
  "THIRD_PARTY_NOTICES.md",
  "THIRD_PARTY_LICENSES/Apache-2.0.txt",
  "THIRD_PARTY_LICENSES/MIT.txt",
];
const registry = "registry+https://github.com/rust-lang/crates.io-index";

test("owned rules preserve exactly the existing formatting and license tuples", () => {
  for (const policy of policies) {
    const legacy = JSON.parse(
      readFileSync(
        resolve(
          root,
          `.github/security/openchat-${policy}-security-baseline.json`,
        ),
        "utf8",
      ),
    );
    const fields =
      policy === "pr1"
        ? ["baseCommit", "format", "introducedRustPackages"]
        : ["directRustPackages", "workspaceOnlyPackages"];
    assert.deepEqual(
      ownedSecurityRules(policy),
      Object.fromEntries(fields.map((field) => [field, legacy[field]])),
    );
  }
});

test("rules reject unknown policy and isolate caller mutations", () => {
  assert.throws(() => ownedSecurityRules("pr3"), /Unknown owned-check/);
  const before = ownedSecurityRules("pr1");
  const changed = ownedSecurityRules("pr1");
  changed.format.extensions.length = 0;
  changed.introducedRustPackages.length = 0;
  assert.deepEqual(ownedSecurityRules("pr1"), before);
});

function fixture(policy) {
  const rules = ownedSecurityRules(policy);
  return {
    policy,
    root,
    rules,
    notices,
    packages:
      policy === "pr1"
        ? rules.introducedRustPackages.map((pkg) => ({
            ...pkg,
            source: registry,
          }))
        : [
            ...rules.directRustPackages,
            ...rules.workspaceOnlyPackages.map((pkg) => ({
              name: pkg.name,
              source: null,
              manifest_path: resolve(root, pkg.manifest),
            })),
          ],
    changed: [
      "frontend/app/src/a.ts",
      "frontend/app/src/space name.svelte",
      "frontend/app/src/config.json",
      "frontend/app/src/config.mjs",
      "frontend/app/src/file.js",
      "frontend/app/src/upper.TS",
      "frontend/app/src/not-selected.md",
      "backend/example.ts",
      "frontend/tauri-plugin-oc/permissions/autogenerated/generated.json",
      "frontend/tauri-plugin-oc/permissions/schemas/generated.json",
      "frontend/src-tauri/THIRD_PARTY_LICENSES/verbatim.json",
      "frontend/src-tauri/THIRD_PARTY_NOTICES.md",
    ],
    untracked: ["frontend/app/src/untracked.ts", "frontend/app/src/a.ts"],
  };
}

// Execute the real CLI with synthetic Git/Cargo/formatter results. No command
// other than this instrumented Node child can run; no inventory is collected.
function hook(input) {
  const source = `
    import child from "node:child_process";
    import fs from "node:fs";
    import http from "node:http";
    import https from "node:https";
    import net from "node:net";
    import tls from "node:tls";
    import dns from "node:dns";
    import { basename, resolve } from "node:path";
    import { syncBuiltinESMExports } from "node:module";
    const f = ${JSON.stringify(input)};
    const trip = (reason) => { process.stderr.write("OWNED_TRIP:" + reason + "\\n"); process.exit(86); };
    const record = (name, value) => process.stderr.write("OWNED_" + name + ":" + JSON.stringify(value) + "\\n");
    for (const name of ["spawn", "spawnSync", "exec", "execSync", "execFile", "execFileSync", "fork"]) child[name] = () => trip("subprocess:" + name);
    for (const mod of [http, https]) for (const name of ["request", "get"]) mod[name] = () => trip("network");
    for (const name of ["connect", "createConnection"]) net[name] = () => trip("network");
    tls.connect = () => trip("network");
    for (const name of ["lookup", "resolve", "resolve4", "resolve6"]) { dns[name] = () => trip("network"); dns.promises[name] = () => trip("network"); }
    globalThis.fetch = () => trip("network");
    globalThis.WebSocket = class { constructor() { trip("network"); } };
    const read = fs.readFileSync;
    const exists = fs.existsSync;
    fs.readFileSync = function(path, ...args) {
      const p = String(path).replaceAll(String.fromCharCode(92), "/");
      if (/openchat-pr[12]-security-baseline\\.json$/u.test(p)) trip("baseline");
      if (/(?:Cargo\\.lock|package-lock\\.json)$/u.test(p)) trip("broad-lock");
      if (p.endsWith("frontend/src-tauri/tauri.conf.json")) {
        record("NOTICES", f.notices);
        return JSON.stringify({ bundle: { resources: f.notices.filter((n) => n !== f.missingResource) } });
      }
      const direct = (f.rules.directRustPackages ?? []).filter((pkg) => p === resolve(f.root, pkg.manifest).replaceAll(String.fromCharCode(92), "/"));
      if (direct.length) return direct.filter((pkg) => pkg.name !== f.missingEdge).map((pkg) => pkg.name + " = { workspace = true }").join("\\n");
      return read.call(this, path, ...args);
    };
    fs.existsSync = function(path) {
      const p = String(path).replaceAll(String.fromCharCode(92), "/");
      const notice = f.notices.find((name) => p.endsWith("frontend/src-tauri/" + name));
      if (notice) return notice !== f.missingNotice;
      return exists(path);
    };
    child.spawnSync = (command, args, options) => {
      if (options?.shell) trip("shell");
      const name = basename(command).toLowerCase();
      if (["git", "git.exe"].includes(name)) {
        const expectedBase = f.baseOverride || f.rules.baseCommit;
        const safe = ["-c", "safe.directory=" + resolve(f.root).replaceAll(String.fromCharCode(92), "/")];
        const diff = [...safe, "diff", "--name-only", f.ci ? expectedBase + "...HEAD" : expectedBase, "--"];
        const untracked = [...safe, "ls-files", "--others", "--exclude-standard"];
        const isDiff = JSON.stringify(args) === JSON.stringify(diff);
        if (!isDiff && JSON.stringify(args) !== JSON.stringify(untracked)) trip("unexpected-git");
        if (f.ci && !isDiff) trip("ci-untracked");
        record("GIT", args);
        return { status: f.gitExit ?? 0, stdout: (isDiff ? f.changed : f.untracked).join("\\n"), stderr: "git fixture" };
      }
      if (["cargo", "cargo.exe"].includes(name)) {
        const expected = ["metadata", "--locked", "--offline", "--format-version", "1", ...(f.policy === "pr1" ? ["--features", "inference"] : [])];
        if (JSON.stringify(args) !== JSON.stringify(expected)) trip("unexpected-cargo");
        record("METADATA", args);
        return { status: f.cargoExit ?? 0, stdout: f.badJson ? "not json" : JSON.stringify({ packages: f.packages }), stderr: "cargo fixture" };
      }
      if (command === process.execPath && args[0] === resolve(f.root, "frontend/node_modules/prettier/bin/prettier.cjs") && args[1] === "--plugin=prettier-plugin-svelte" && args[2] === "--check" && options.cwd === resolve(f.root, "frontend")) {
        record("FORMAT", args.slice(3));
        return { status: f.formatExit ?? 0, stdout: "formatter fixture", stderr: "formatter details" };
      }
      trip("unexpected-command");
    };
    syncBuiltinESMExports();
    process.stderr.write("OWNED_READY\\n");
  `;
  return (
    "data:text/javascript;base64," + Buffer.from(source).toString("base64")
  );
}

function run(policy, modes, mutate = () => {}) {
  const data = fixture(policy);
  mutate(data);
  return spawnSync(
    process.execPath,
    [
      "--import",
      hook(data),
      resolve(root, `scripts/check_openchat_${policy}_security.mjs`),
      ...modes,
    ],
    {
      cwd: root,
      encoding: "utf8",
      timeout: 10000,
      maxBuffer: 1024 * 1024,
      env: {
        ...process.env,
        NODE_OPTIONS: "",
        CI: data.ci ? "true" : "false",
        PR_BASE_SHA: data.baseOverride ?? "",
        CARGO_AUDIT_BIN: "must-not-run",
        CARGO_CYCLONEDX_BIN: "must-not-run",
        SBOM_OUTPUT: "must-not-write",
      },
    },
  );
}
function checked(result, passes) {
  assert.equal(result.error, undefined);
  assert.equal(result.signal, null);
  assert.match(result.stderr, /OWNED_READY/u);
  assert.doesNotMatch(result.stderr, /OWNED_TRIP:/u);
  assert.equal(result.status, passes ? 0 : 1, result.stdout + result.stderr);
  if (passes) {
    assert.match(result.stdout, /offline owned checks passed/u);
    assert.match(
      result.stdout,
      /advisory and release acceptance not assessed/u,
    );
    assert.doesNotMatch(result.stdout, /security policy passed/u);
  } else
    assert.doesNotMatch(result.stdout, /checks passed|security policy passed/u);
}
function records(result, name) {
  return result.stderr
    .split(/\r?\n/u)
    .filter((line) => line.startsWith(`OWNED_${name}:`))
    .map((line) => JSON.parse(line.slice(`OWNED_${name}:`.length)));
}

for (const policy of policies) {
  test(`${policy}: license-only performs the owned checks without baseline/lock reads`, () => {
    const result = run(policy, ["licenses"]);
    checked(result, true);
    assert.equal(records(result, "METADATA").length, 1);
    assert.equal(records(result, "GIT").length, 0);
    assert.equal(records(result, "NOTICES").length, policy === "pr1" ? 1 : 0);
  });
  for (const [label, mutate] of [
    ["missing package", (f) => f.packages.shift()],
    ["duplicate package", (f) => f.packages.push({ ...f.packages[0] })],
    ["changed version", (f) => (f.packages[0].version = "999.0.0")],
    ["changed license", (f) => (f.packages[0].license = "unknown")],
    [
      "changed source",
      (f) =>
        (f.packages[0].source = "git+https://example.invalid/repo#deadbeef"),
    ],
    ["nonzero metadata exit with valid JSON", (f) => (f.cargoExit = 1)],
    ["malformed metadata", (f) => (f.badJson = true)],
  ])
    test(`${policy}: licenses reject ${label}`, () => {
      const result = run(policy, ["licenses"], mutate);
      checked(result, false);
      assert.equal(records(result, "METADATA").length, 1);
    });
  test(`${policy}: ci and mixed ci modes still reach the original fail-closed baseline`, () => {
    for (const modes of [
      ["ci"],
      ["ci", "licenses"],
      ...(policy === "pr1" ? [["format", "ci"]] : []),
    ]) {
      const result = run(policy, modes);
      assert.equal(result.status, 86, result.stderr);
      assert.match(result.stderr, /OWNED_TRIP:baseline/u);
      assert.equal(records(result, "METADATA").length, 0);
      assert.equal(records(result, "FORMAT").length, 0);
    }
  });
}

for (const notice of notices)
  for (const kind of ["missingNotice", "missingResource"])
    test(`pr1: rejects ${kind} ${notice}`, () =>
      checked(
        run("pr1", ["licenses"], (f) => (f[kind] = notice)),
        false,
      ));

test("pr1: format-only checks exactly the existing candidate rules including untracked paths", () => {
  const result = run("pr1", ["format"]);
  checked(result, true);
  assert.deepEqual(records(result, "FORMAT").flat(), [
    "app/src/a.ts",
    "app/src/config.json",
    "app/src/config.mjs",
    "app/src/file.js",
    "app/src/space name.svelte",
    "app/src/untracked.ts",
    "app/src/upper.TS",
  ]);
  assert.equal(records(result, "GIT").length, 2);
  assert.equal(records(result, "METADATA").length, 0);
  assert.match(result.stdout, /checked 7 .*excluded 4/u);
});
test("pr1: CI formatting preserves explicit comparison base and excludes local untracked files", () => {
  const result = run("pr1", ["format"], (f) => {
    f.ci = true;
    f.baseOverride = "a".repeat(40);
  });
  checked(result, true);
  assert.equal(records(result, "GIT").length, 1);
  assert.equal(records(result, "FORMAT").flat().length, 6);
});
test("pr1: combined format/licenses executes both without advisory acceptance", () => {
  const result = run("pr1", ["format", "licenses"]);
  checked(result, true);
  assert.equal(records(result, "FORMAT").length, 1);
  assert.equal(records(result, "METADATA").length, 1);
});
test("pr1: actual Git and formatter failures stay fatal", () => {
  for (const field of ["gitExit", "formatExit"])
    checked(
      run("pr1", ["format"], (f) => (f[field] = 1)),
      false,
    );
});

if (policies.includes("pr2")) {
  for (const pkg of ownedSecurityRules("pr2").directRustPackages)
    test(`pr2: rejects missing direct owner edge ${pkg.name}`, () =>
      checked(
        run("pr2", ["licenses"], (f) => (f.missingEdge = pkg.name)),
        false,
      ));
  for (const [label, mutate] of [
    ["missing fixture", (f) => f.packages.pop()],
    ["non-path fixture", (f) => (f.packages.at(-1).source = registry)],
    [
      "wrong fixture owner",
      (f) =>
        (f.packages.at(-1).manifest_path = resolve(root, "wrong/Cargo.toml")),
    ],
  ])
    test(`pr2: rejects ${label}`, () =>
      checked(run("pr2", ["licenses"], mutate), false));
}
