// Existing formatting and owned license rules only, separated from historical
// whole-lockfile advisory baselines. This is not dependency/advisory acceptance.
const modelRules = {
  baseCommit: "3c49a73021ab4c660bced03ae4281db5a4b36cd8",
  format: {
    sourceRoot: "frontend/",
    extensions: [".js", ".json", ".mjs", ".svelte", ".ts"],
    excludedPrefixes: {
      "frontend/src-tauri/THIRD_PARTY_LICENSES/":
        "Verbatim third-party license texts are reviewed as native legal metadata, not reformatted.",
      "frontend/tauri-plugin-oc/permissions/autogenerated/":
        "Generated by the Tauri plugin permission tooling; regenerate it instead of rewriting it with Prettier.",
      "frontend/tauri-plugin-oc/permissions/schemas/":
        "Generated by the Tauri plugin permission tooling; regenerate it instead of rewriting it with Prettier.",
    },
    excludedFiles: {
      "frontend/src-tauri/THIRD_PARTY_NOTICES.md":
        "Native third-party notice metadata is reviewed for content and bundled verbatim.",
    },
  },
  introducedRustPackages: [
    { name: "bindgen", version: "0.72.1", license: "BSD-3-Clause" },
    { name: "cexpr", version: "0.6.0", license: "Apache-2.0/MIT" },
    { name: "clang-sys", version: "1.9.1", license: "Apache-2.0" },
    {
      name: "find_cuda_helper",
      version: "0.2.0",
      license: "MIT OR Apache-2.0",
    },
    { name: "libloading", version: "0.8.9", license: "ISC" },
    { name: "llama-cpp-2", version: "0.1.150", license: "MIT OR Apache-2.0" },
    {
      name: "llama-cpp-sys-2",
      version: "0.1.150",
      license: "MIT OR Apache-2.0",
    },
    { name: "memo-map", version: "0.3.3", license: "Apache-2.0" },
    { name: "minijinja", version: "2.21.0", license: "Apache-2.0" },
    { name: "minijinja-contrib", version: "2.21.0", license: "Apache-2.0" },
    { name: "ntapi", version: "0.4.3", license: "Apache-2.0 OR MIT" },
    { name: "prettyplease", version: "0.2.37", license: "MIT OR Apache-2.0" },
    { name: "shlex", version: "1.3.0", license: "MIT OR Apache-2.0" },
    { name: "sysinfo", version: "0.33.1", license: "MIT" },
    { name: "windows", version: "0.57.0", license: "MIT OR Apache-2.0" },
    { name: "windows-core", version: "0.57.0", license: "MIT OR Apache-2.0" },
    {
      name: "windows-implement",
      version: "0.57.0",
      license: "MIT OR Apache-2.0",
    },
    {
      name: "windows-interface",
      version: "0.57.0",
      license: "MIT OR Apache-2.0",
    },
    { name: "windows-result", version: "0.1.2", license: "MIT OR Apache-2.0" },
  ],
};
const appRules = {
  directRustPackages: [
    {
      name: "aes-gcm",
      version: "0.10.3",
      license: "Apache-2.0 OR MIT",
      source: "registry+https://github.com/rust-lang/crates.io-index",
      manifest: "backend/libraries/ecies_payload/Cargo.toml",
    },
    {
      name: "hkdf",
      version: "0.13.0",
      license: "MIT OR Apache-2.0",
      source: "registry+https://github.com/rust-lang/crates.io-index",
      manifest: "backend/libraries/ecies_payload/Cargo.toml",
    },
    {
      name: "subtle",
      version: "2.6.1",
      license: "BSD-3-Clause",
      source: "registry+https://github.com/rust-lang/crates.io-index",
      manifest: "backend/canisters/action_inbox/impl/Cargo.toml",
    },
    {
      name: "zeroize",
      version: "1.9.0",
      license: "Apache-2.0 OR MIT",
      source: "registry+https://github.com/rust-lang/crates.io-index",
      manifest: "backend/canisters/user_index/impl/Cargo.toml",
    },
  ],
  workspaceOnlyPackages: [
    {
      name: "ai_app_verifier_test_canister_impl",
      manifest:
        "backend/external_canisters/ai_app_verifier/test_impl/Cargo.toml",
    },
  ],
};

export function ownedSecurityRules(policyName) {
  if (!["pr1", "pr2"].includes(policyName)) {
    throw new Error("Unknown owned-check policy: " + policyName);
  }
  // Callers cannot mutate the reviewed constants for a subsequent invocation.
  return structuredClone(policyName === "pr1" ? modelRules : appRules);
}
