// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "../shared/TSBigIntWithDefault";
import type { TSBytes } from "../shared/TSBytes";

export type ProposalsBotExecuteGenericNervousSystemFunction = { function_id: TSBigIntWithDefault, payload: TSBytes, };
