// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountICRC1 } from "../shared/AccountICRC1";
import type { ProposalsBotTreasury } from "./ProposalsBotTreasury";
import type { TSBigIntWithDefault } from "../shared/TSBigIntWithDefault";

export type ProposalsBotTransferSnsTreasuryFunds = { treasury: ProposalsBotTreasury, amount: TSBigIntWithDefault, to: AccountICRC1, memo?: bigint | undefined, };
