// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountICRC1 } from "../shared/AccountICRC1";

export type ProposalsBotMintSnsTokens = { amount: bigint, to: AccountICRC1, memo?: bigint | undefined, };
