import DRange from "drange";
import type { MessageContent, Message, ReplyContext, StaleMessage, CryptocurrencyContent, CompletedCryptocurrencyTransfer, FailedCryptocurrencyTransfer, GroupPermissions, PermissionRole, PendingCryptocurrencyWithdrawal, ThreadSummary, ListNervousSystemFunctionsResponse } from "../../domain/chat/chat";
import type { User } from "../../domain/user/user";
import type { ApiMessageContent, ApiMessage, ApiReplyContext, ApiUpdatedMessage, ApiCryptoContent, ApiNnsPendingCryptoTransaction, ApiNnsCompletedCryptoTransaction, ApiNnsFailedCryptoTransaction, ApiSnsCompletedCryptoTransaction, ApiSnsFailedCryptoTransaction, ApiMessageIndexRange, ApiUser, ApiGroupPermissions, ApiPermissionRole, ApiCryptocurrency, ApiThreadSummary } from "../user/candid/idl";
import type { Cryptocurrency } from "../../domain/crypto";
import type { ApiListNervousSystemFunctionsResponse } from "../snsGovernance/candid/idl";
export declare function message(candid: ApiMessage): Message;
export declare function threadSummary(candid: ApiThreadSummary): ThreadSummary;
export declare function updatedMessage(candid: ApiUpdatedMessage): StaleMessage;
export declare function apiMessageIndexRanges(ranges: ApiMessageIndexRange[]): DRange;
export declare function messageContent(candid: ApiMessageContent, sender: string): MessageContent;
export declare function apiUser(domain: User): ApiUser;
export declare function token(_candid: ApiCryptocurrency): Cryptocurrency;
export declare function apiToken(_token: Cryptocurrency): ApiCryptocurrency;
export declare function completedCryptoTransfer(candid: ApiNnsCompletedCryptoTransaction | ApiSnsCompletedCryptoTransaction, sender: string, recipient: string): CompletedCryptocurrencyTransfer;
export declare function failedCryptoTransfer(candid: ApiNnsFailedCryptoTransaction | ApiSnsFailedCryptoTransaction, recipient: string): FailedCryptocurrencyTransfer;
export declare function groupPermissions(candid: ApiGroupPermissions): GroupPermissions;
export declare function apiGroupPermissions(permissions: GroupPermissions): ApiGroupPermissions;
export declare function apiPermissionRole(permissionRole: PermissionRole): ApiPermissionRole;
export declare function permissionRole(candid: ApiPermissionRole): PermissionRole;
export declare function apiReplyContextArgs(domain: ReplyContext, replyingToChatId?: string): ApiReplyContext;
export declare function apiMessageContent(domain: MessageContent): ApiMessageContent;
export declare function apiOptional<D, A>(mapper: (d: D) => A, domain: D | undefined): [] | [A];
export declare function apiPendingCryptoContent(domain: CryptocurrencyContent): ApiCryptoContent;
export declare function apiPendingCryptocurrencyWithdrawal(domain: PendingCryptocurrencyWithdrawal): ApiNnsPendingCryptoTransaction;
export declare function nervousSystemFunctions(candid: ApiListNervousSystemFunctionsResponse): ListNervousSystemFunctionsResponse;
