[package]
name = "multi_user_canister_impl"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
canister_api_macros = { path = "../../../libraries/canister_api_macros" }
canister_logger = { path = "../../../libraries/canister_logger" }
canister_state_macros = { path = "../../../libraries/canister_state_macros" }
canister_timer_jobs = { path = "../../../libraries/canister_timer_jobs" }
canister_tracing_macros = { path = "../../../libraries/canister_tracing_macros" }
chat_events = { path = "../../../libraries/chat_events" }
community_canister = { path = "../../community/api" }
community_canister_c2c_client = { path = "../../community/c2c_client" }
constants = { path = "../../../libraries/constants" }
direct_chat = { path = "../../../libraries/direct_chat" }
escrow_canister = { path = "../../escrow/api" }
event_store_types = { workspace = true, features = ["json"] }
git_commit_id = { path = "../../../libraries/git_commit_id" }
group_canister = { path = "../../group/api" }
group_canister_c2c_client = { path = "../../group/c2c_client" }
group_index_canister = { path = "../../group_index/api" }
group_index_canister_c2c_client = { path = "../../group_index/c2c_client" }
http_request = { path = "../../../libraries/http_request" }
icrc_ledger_canister_c2c_client = { path = "../../../external_canisters/icrc_ledger/c2c_client" }
icrc-ledger-types = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-stable-structures = { workspace = true }
ledger_utils = { path = "../../../libraries/ledger_utils" }
local_user_index_canister = { path = "../../local_user_index/api" }
local_user_index_canister_c2c_client = { path = "../../local_user_index/c2c_client" }
msgpack = { path = "../../../libraries/msgpack" }
oc_error_codes = { path = "../../../libraries/error_codes" }
multi_user_canister = { path = "../api" }
rand = { workspace = true }
serde = { workspace = true }
stable_memory = { path = "../../../libraries/stable_memory" }
stable_memory_map = { path = "../../../libraries/stable_memory_map" }
timer_job_queues = { path = "../../../libraries/timer_job_queues" }
tracing = { workspace = true }
types = { path = "../../../libraries/types" }
user_canister = { path = "../../user/api" }
user_canister_c2c_client = { path = "../../user/c2c_client" }
user_core = { path = "../../../libraries/user_core" }
utils = { path = "../../../libraries/utils" }
