// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "../../shared/MessageId";
import type { MessageIndex } from "../../shared/MessageIndex";
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";
import type { UserId } from "../../shared/UserId";

export type UserDeleteMessagesArgs = { user_id: UserId, thread_root_message_index?: MessageIndex | undefined, 
/**
 * @default []
 */
message_ids: Array<MessageId>, correlation_id: TSBigIntWithDefault, };
