// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "../../ChannelId";
import type { UserId } from "../../shared/UserId";

export type CommunitySearchChannelArgs = { channel_id: ChannelId, search_term: string, max_results: number, users?: Array<UserId> | undefined, };
