// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageMatch } from "../../shared/MessageMatch";

export type CommunitySearchChannelSuccessResult = { 
/**
 * @default []
 */
matches: Array<MessageMatch>, };
