// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type LocalUserIndexChatEventsEventsWindowArgs = { mid_point: TSNumberWithDefault, max_messages: TSNumberWithDefault, max_events: TSNumberWithDefault, };
