// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventIndex } from "../../shared/EventIndex";

export type LocalUserIndexChatEventsEventsPageArgs = { 
/**
 * @default 0
 */
start_index: EventIndex, 
/**
 * @default false
 */
ascending: boolean, 
/**
 * @default 0
 */
max_messages: number, 
/**
 * @default 0
 */
max_events: number, };
