// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventsResponse } from "../../shared/EventsResponse";
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";

export type LocalUserIndexChatEventsEventsResponse = { "Success": EventsResponse } | "NotFound" | { "ReplicaNotUpToDate": TSBigIntWithDefault } | { "InternalError": string };
