// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserIndexChatEventsEventsByIndexArgs } from "./LocalUserIndexChatEventsEventsByIndexArgs";
import type { LocalUserIndexChatEventsEventsPageArgs } from "./LocalUserIndexChatEventsEventsPageArgs";
import type { LocalUserIndexChatEventsEventsWindowArgs } from "./LocalUserIndexChatEventsEventsWindowArgs";

export type LocalUserIndexChatEventsEventsSelectionCriteria = { "Page": LocalUserIndexChatEventsEventsPageArgs } | { "ByIndex": LocalUserIndexChatEventsEventsByIndexArgs } | { "Window": LocalUserIndexChatEventsEventsWindowArgs };
