// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionUpdateAccessGate } from "../../shared/OptionUpdateAccessGate";
import type { OptionUpdateAccessGateConfig } from "../../shared/OptionUpdateAccessGateConfig";
import type { OptionUpdateDocument } from "../../shared/OptionUpdateDocument";
import type { OptionUpdateU64 } from "../../shared/OptionUpdateU64";
import type { OptionalGroupPermissions } from "../../shared/OptionalGroupPermissions";
import type { UpdatedRules } from "../../shared/UpdatedRules";

export type GroupUpdateGroupArgs = { name?: string | undefined, description?: string | undefined, rules?: UpdatedRules | undefined, 
/**
 * @default NoChange
 */
avatar: OptionUpdateDocument, permissions_v2?: OptionalGroupPermissions | undefined, 
/**
 * @default NoChange
 */
events_ttl: OptionUpdateU64, 
/**
 * @default NoChange
 */
gate: OptionUpdateAccessGate, 
/**
 * @default NoChange
 */
gate_config: OptionUpdateAccessGateConfig, public?: boolean | undefined, messages_visible_to_non_members?: boolean | undefined, correlation_id: bigint, };
