// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Version } from "../../shared/Version";

export type GroupUpdateGroupSuccessResult = { rules_version?: Version | undefined, };
