// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessTokenType } from "../../shared/AccessTokenType";
import type { Chat } from "../../shared/Chat";

export type LocalUserIndexAccessTokenArgs = { token_type: AccessTokenType, chat: Chat, };
