// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type CommunityFollowThreadArgs = { channel_id: bigint, thread_root_message_index: TSNumberWithDefault, };
