#!/bin/bash

# Registers the SNS generic functions needed to govern the personhood
# verification system, as separate AddGenericNervousSystemFunction
# proposals:
#
#   11000 commit_model                          (personhood_verifier)
#   11001 set_uniqueness_thresholds             (personhood_verifier)
#
# 11000 starts a new id range for the personhood_verifier at the time of
# writing; re-check against
# `list_nervous_system_functions` on the SNS governance canister before
# running. Validators follow the OpenChat convention: the target canister
# itself exposes a `<method>_validate` query generated by the #[proposal]
# macro.
#
# Prerequisite: the personhood_verifier canister must exist on the target
# network and be present in canister_ids.json (its id is resolved via dfx).

# Set current directory to the OC root
SCRIPT=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT")
cd $SCRIPT_DIR/../..

# Set env variables based on .env file
set -o allexport; source .env; set +o allexport
./sns/scripts/utils/setup_env.sh

PERSONHOOD_VERIFIER_CANISTER_ID=$(dfx -qq canister --network $NETWORK id personhood_verifier)
URL="https://github.com/open-chat-labs/open-chat/issues/9072"

function register {
    FUNCTION_ID=$1
    FUNCTION_NAME=$2
    FUNCTION_DESC=$3
    TOPIC=$4
    CANISTER_ID=$5
    METHOD=$6

    TITLE="Register SNS function $FUNCTION_ID ($FUNCTION_NAME)"

    PROPOSAL="(record { title=\"$TITLE\"; url=\"$URL\"; summary=\"$FUNCTION_DESC\"; action=opt variant {AddGenericNervousSystemFunction = record {id=($FUNCTION_ID:nat64); name=\"$FUNCTION_NAME\"; description=opt\"$FUNCTION_DESC\"; function_type=opt variant {GenericNervousSystemFunction=record{validator_canister_id=opt principal\"$CANISTER_ID\"; target_canister_id=opt principal\"$CANISTER_ID\"; validator_method_name=opt\"${METHOD}_validate\"; target_method_name=opt\"$METHOD\"; topic=opt variant { $TOPIC }}}}}})"

    ./sns/scripts/utils/submit_proposal.sh "$PROPOSAL"
}

register 11000 \
    "Commit a personhood verification model" \
    "Activates a face verification model whose chunks have already been uploaded (inert) to the personhood_verifier canister, but only if the assembled bytes hash to exactly the sha256 value pinned in the proposal payload. Committing a new embedding model bumps the model version and starts the 90 day re-verification window for proofs of the previous version." \
    "DappCanisterManagement" \
    $PERSONHOOD_VERIFIER_CANISTER_ID \
    "commit_model"

register 11001 \
    "Set personhood uniqueness thresholds" \
    "Tunes the cosine-similarity bands (clear / duplicate_retry / duplicate) the personhood_verifier uses to decide whether a face embedding is a duplicate of an already enrolled user. The right values depend on the enrolled population size, which grows, so they stay governable rather than baked into the wasm. Must satisfy clear <= duplicate_retry <= duplicate." \
    "ApplicationBusinessLogic" \
    $PERSONHOOD_VERIFIER_CANISTER_ID \
    "set_uniqueness_thresholds"

# Cleanup
./sns/scripts/utils/cleanup_env.sh
