// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferralMetrics } from "./ReferralMetrics";

export type Response = { "Success": ReferralMetrics };
