// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserSummary } from "../../UserSummary";

export type UserIndex_User_Response = { "Success": UserSummary } | "UserNotFound";
