import type { CheckUsernameResponse, SetUsernameResponse, CurrentUserResponse, CreateChallengeResponse, SubmitPhoneNumberResponse, ConfirmPhoneNumberResponse, PhoneNumber, ResendCodeResponse, UsersResponse, UserSummary, PartialUserSummary, RegisterUserResponse, PhoneStatus, UpgradeStorageResponse } from "../../domain/user/user";
import type { ApiCheckUsernameResponse, ApiConfirmPhoneNumberResponse, ApiCreateChallengeResponse, ApiCurrentUserResponse, ApiPartialUserSummary, ApiPhoneNumber, ApiPhoneStatus, ApiRegisterUserResponse, ApiResendCodeResponse, ApiSearchResponse, ApiSetUsernameResponse, ApiSubmitPhoneNumberResponse, ApiUpgradeStorageResponse, ApiUsersResponse, ApiUserSummary } from "./candid/idl";
export declare function userSearchResponse(candid: ApiSearchResponse): UserSummary[];
export declare function usersResponse(candid: ApiUsersResponse): UsersResponse;
export declare function partialUserSummary(candid: ApiPartialUserSummary, timestamp: bigint): PartialUserSummary;
export declare function userSummary(candid: ApiUserSummary, timestamp: bigint): UserSummary;
export declare function submitPhoneNumberResponse(candid: ApiSubmitPhoneNumberResponse): SubmitPhoneNumberResponse;
export declare function createChallengeResponse(candid: ApiCreateChallengeResponse): CreateChallengeResponse;
export declare function registerUserResponse(candid: ApiRegisterUserResponse): RegisterUserResponse;
export declare function confirmPhoneNumber(candid: ApiConfirmPhoneNumberResponse): ConfirmPhoneNumberResponse;
export declare function phoneNumber(candid: ApiPhoneNumber): PhoneNumber;
export declare function upgradeStorageResponse(candid: ApiUpgradeStorageResponse): UpgradeStorageResponse;
export declare function currentUserResponse(candid: ApiCurrentUserResponse): CurrentUserResponse;
export declare function phoneStatus(candid: ApiPhoneStatus): PhoneStatus;
export declare function checkUsernameResponse(candid: ApiCheckUsernameResponse): CheckUsernameResponse;
export declare function setUsernameResponse(candid: ApiSetUsernameResponse): SetUsernameResponse;
export declare function resendCodeResponse(candid: ApiResendCodeResponse): ResendCodeResponse;
