// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvalidPollReason } from "../../shared/InvalidPollReason";
import type { UserSendMessageV2SuccessResult } from "./UserSendMessageV2SuccessResult";
import type { UserSendMessageV2TransferSuccessV2Result } from "./UserSendMessageV2TransferSuccessV2Result";

export type UserSendMessageV2Response = { "Success": UserSendMessageV2SuccessResult } | { "TransferSuccessV2": UserSendMessageV2TransferSuccessV2Result } | "MessageEmpty" | { "TextTooLong": number } | "RecipientBlocked" | "RecipientNotFound" | { "InvalidPoll": InvalidPollReason } | { "InvalidRequest": string } | { "TransferFailed": string } | "TransferCannotBeZero" | "TransferCannotBeToSelf" | { "P2PSwapSetUpFailed": string } | "DuplicateMessageId" | "UserSuspended" | "PinRequired" | { "PinIncorrect": bigint } | { "TooManyFailedPinAttempts": bigint } | { "InternalError": string };
