SCRIPT=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT")
cd $SCRIPT_DIR

pwd

mergedFile=./merged.ts

echo "// Autogenerated by \`ts_gen.sh\`. Do not edit manually\n" > $mergedFile

for filename in $(find ./ts_bindings -name '*.ts'); do
    [ -e "$filename" ] || continue

    echo $filename

    cat $filename | while read line
    do
        if [[ $line == export* ]]; then
            echo $line >> $mergedFile
        fi
    done
done

npm run ts-to-zod $mergedFile ./ts_bindings/zod.ts
