// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "../../shared/UserId";

export type CommunityUpdateUserGroupArgs = { 
/**
 * @default 0
 */
user_group_id: number, name?: string | undefined, 
/**
 * @default []
 */
users_to_add: Array<UserId>, 
/**
 * @default []
 */
users_to_remove: Array<UserId>, };
