// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Principal } from "../../Principal";

export type GroupIndex_MarkLocalGroupIndexFull_Args = { canister_id: Principal, full: boolean, };
