// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupIndex_MarkLocalGroupIndexFull_Response = "Success" | "LocalGroupIndexNotFound" | "NotAuthorized" | { "InternalError": string };
