// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityMatch } from "../../shared/CommunityMatch";

export type GroupIndexExploreCommunitiesSuccessResult = { matches: Array<CommunityMatch>, total: number, };
