// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupIndex_ExploreCommunities_SuccessResult } from "./GroupIndex_ExploreCommunities_SuccessResult";

export type GroupIndex_ExploreCommunities_Response = { "Success": GroupIndex_ExploreCommunities_SuccessResult } | { "TermTooShort": number } | { "TermTooLong": number } | "InvalidTerm" | "InvalidFlags";
