// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommunityAddMembersToChannelUserFailedError } from "./CommunityAddMembersToChannelUserFailedError";
import type { UserId } from "../../shared/UserId";

export type CommunityAddMembersToChannelPartialSuccessResult = { 
/**
 * @default []
 */
users_added: Array<UserId>, 
/**
 * @default []
 */
users_already_in_channel: Array<UserId>, 
/**
 * @default []
 */
users_limit_reached: Array<UserId>, 
/**
 * @default []
 */
users_failed_with_error: Array<CommunityAddMembersToChannelUserFailedError>, };
