// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndex_PayForDiamondMembership_SuccessResult } from "./UserIndex_PayForDiamondMembership_SuccessResult";

export type UserIndex_PayForDiamondMembership_Response = { "Success": UserIndex_PayForDiamondMembership_SuccessResult } | "AlreadyLifetimeDiamondMember" | "CurrencyNotSupported" | "PriceMismatch" | "PaymentAlreadyInProgress" | "UserNotFound" | { "InsufficientFunds": bigint } | { "TransferFailed": string } | { "InternalError": string };
