// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Principal } from "../../Principal";

export type UserIndex_SubmitProofOfUniquePersonhood_Args = { user_ii_principal: Principal, credential_jwt: string, };
