// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadPreview } from "../../shared/ThreadPreview";

export type CommunityThreadPreviewsSuccessResult = { threads: Array<ThreadPreview>, timestamp: bigint, };
