// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "../../ChannelId";
import type { MessageId } from "../../shared/MessageId";
import type { MessageIndex } from "../../shared/MessageIndex";

export type CommunityReportMessageArgs = { channel_id: ChannelId, thread_root_message_index?: MessageIndex | undefined, message_id: MessageId, delete: boolean, };
