// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "../../shared/ChatId";
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";

export type UserLeaveGroupArgs = { chat_id: ChatId, correlation_id: TSBigIntWithDefault, };
