// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSBigIntWithDefault } from "../../shared/TSBigIntWithDefault";

export type CommunitySummaryUpdatesArgs = { invite_code?: bigint | undefined, updates_since: TSBigIntWithDefault, };
