// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "../ChannelId";
import type { CommunityId } from "../shared/CommunityId";
import type { UserChannelSummaryUpdates } from "./UserChannelSummaryUpdates";

export type UserCommunitySummaryUpdates = { community_id: CommunityId, channels: Array<UserChannelSummaryUpdates>, index?: number | undefined, archived?: boolean | undefined, pinned?: Array<ChannelId> | undefined, };
