// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "../shared/ChatId";
import type { MessageIndex } from "../shared/MessageIndex";
import type { TSPrincipal } from "../shared/TSPrincipal";

export type UserGroupChatSummary = { chat_id: ChatId, local_user_index_canister_id: TSPrincipal, read_by_me_up_to?: MessageIndex, threads_read: Record<MessageIndex, MessageIndex>, archived: boolean, date_read_pinned?: bigint, };
