// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "../ChannelId";
import type { Chat } from "../shared/Chat";
import type { ChatId } from "../shared/ChatId";
import type { CommunityId } from "../shared/CommunityId";

export type UserChatInList = { "Direct": ChatId } | { "Group": ChatId } | { "Favourite": Chat } | { "Community": [CommunityId, ChannelId] };
