// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSNumberWithDefault } from "../../shared/TSNumberWithDefault";

export type CommunityExploreChannelsArgs = { invite_code?: bigint | undefined, search_term?: string | undefined, page_index: TSNumberWithDefault, page_size: TSNumberWithDefault, };
