// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommunityExploreChannelsArgs = { invite_code?: bigint | undefined, search_term?: string | undefined, 
/**
 * @default 0
 */
page_index: number, 
/**
 * @default 0
 */
page_size: number, };
