// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommunityExploreChannelsArgs = { invite_code?: bigint, search_term?: string, page_index: number, page_size: number, };
