// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserCommunitySummary } from "../UserCommunitySummary";

export type UserInitialStateCommunitiesInitial = { 
/**
 * @default []
 */
summaries: Array<UserCommunitySummary>, };
