// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatId } from "../../shared/ChatId";
import type { DirectChatSummary } from "../../shared/DirectChatSummary";

export type UserInitialStateDirectChatsInitial = { summaries: Array<DirectChatSummary>, pinned: Array<ChatId>, };
