// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupChatSummary } from "../../shared/GroupChatSummary";

export type UserInitialStateCachedGroupChatSummaries = { summaries: Array<GroupChatSummary>, timestamp: bigint, };
