// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChitEarned } from "../../shared/ChitEarned";
import type { PinNumberSettings } from "../../shared/PinNumberSettings";
import type { StreakInsurance } from "../../shared/StreakInsurance";
import type { TSBytes } from "../../shared/TSBytes";
import type { UserId } from "../../shared/UserId";
import type { UserInitialStateCommunitiesInitial } from "./UserInitialStateCommunitiesInitial";
import type { UserInitialStateDirectChatsInitial } from "./UserInitialStateDirectChatsInitial";
import type { UserInitialStateFavouriteChatsInitial } from "./UserInitialStateFavouriteChatsInitial";
import type { UserInitialStateGroupChatsInitial } from "./UserInitialStateGroupChatsInitial";
import type { UserMessageActivitySummary } from "../UserMessageActivitySummary";
import type { UserReferral } from "../UserReferral";
import type { UserWalletConfig } from "../UserWalletConfig";

export type UserInitialStateSuccessResult = { timestamp: bigint, direct_chats: UserInitialStateDirectChatsInitial, group_chats: UserInitialStateGroupChatsInitial, favourite_chats: UserInitialStateFavouriteChatsInitial, communities: UserInitialStateCommunitiesInitial, avatar_id?: bigint | undefined, blocked_users: Array<UserId>, suspended: boolean, pin_number_settings?: PinNumberSettings | undefined, local_user_index_canister_id: TSBytes, achievements: Array<ChitEarned>, achievements_last_seen: bigint, total_chit_earned: number, chit_balance: number, streak: number, streak_ends: bigint, streak_insurance?: StreakInsurance | undefined, next_daily_claim: bigint, is_unique_person: boolean, wallet_config: UserWalletConfig, referrals: Array<UserReferral>, message_activity_summary: UserMessageActivitySummary, };
