// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageIndexProjectedAllowance = { byte_limit: bigint, bytes_used: bigint, bytes_used_after_upload: bigint, bytes_used_after_operation: bigint, };
