// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndexChitLeaderboardChitUserBalance } from "./UserIndexChitLeaderboardChitUserBalance";

export type UserIndexChitLeaderboardSuccessResult = { 
/**
 * @default []
 */
all_time: Array<UserIndexChitLeaderboardChitUserBalance>, 
/**
 * @default []
 */
this_month: Array<UserIndexChitLeaderboardChitUserBalance>, 
/**
 * @default []
 */
last_month: Array<UserIndexChitLeaderboardChitUserBalance>, };
