// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserIndexChitLeaderboardChitUserBalance } from "./UserIndexChitLeaderboardChitUserBalance";
import type { UserIndexChitLeaderboardSuccessResult } from "./UserIndexChitLeaderboardSuccessResult";

export type UserIndexChitLeaderboardResponse = { "Success": Array<UserIndexChitLeaderboardChitUserBalance> } | { "SuccessV2": UserIndexChitLeaderboardSuccessResult };
