// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageIndexProjectedAllowance } from "../StorageIndexProjectedAllowance";

export type StorageIndexCanForwardResponse = { "Success": StorageIndexProjectedAllowance } | { "AllowanceExceeded": StorageIndexProjectedAllowance } | "UserNotFound";
