// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferralStats } from "./ReferralStats";

export type MonthSuccessResult = { year: number, month: number, results: Array<ReferralStats>, };
